(in-package :eql)

(let ((window (qnew "QDialog"))
      (label (qnew "QLabel"))
      (line-edit (qnew "QLineEdit"))
      (layout (qnew "QVBoxLayout")))
  (qset window "windowTitle" "My Personal Analyst")
  (qset label "text" "Please enter your <b>Top Secret</b> (you will feel better)")
  (qset line-edit "echoMode" "Password")
  (dolist (w (list label line-edit))
    (qfun layout "addWidget" w))
  (qfun window "setLayout" layout)
  (qconnect line-edit "returnPressed()"
            (lambda ()
              (qlet ((dlg "QProgressDialog"))
                (qset dlg "maximum" 20)
                (qset dlg "labelText"
                      "<h1 style='color:crimson'>Wow!</h1><p>(updating WikiLeaks...)</p>")
                (qfun dlg "show")
                (dotimes (n (qget dlg "maximum"))
                  (sleep 0.1)
                  (qset dlg "value" n)
                  (qprocess-events)))
              (qfun line-edit "clear")))
  (qfun window "show"))
