(defpackage :eql
  (:export
   #:|abortHostLookup.QHostInfo|
   #:|abort|
   #:|about.QMessageBox|
   #:|aboutQt.QMessageBox|
   #:|aboutQt|
   #:|aboutToActivate|
   #:|aboutToClose|
   #:|aboutToHide|
   #:|aboutToQuit|
   #:|aboutToShow|
   #:|absoluteDir|
   #:|absoluteFilePath|
   #:|absolutePath|
   #:|acceleration|
   #:|accept(QGesture*)|
   #:|accept(Qt::GestureType)|
   #:|acceptDrops|
   #:|acceptHoverEvents|
   #:|acceptMode|
   #:|acceptProposedAction|
   #:|acceptRichText|
   #:|acceptTouchEvents|
   #:|acceptedMouseButtons|
   #:|accepted|
   #:|accept|
   #:|accessibleDescription|
   #:|accessibleName|
   #:|accessibleText|
   #:|accumBufferSize|
   #:|accum|
   #:|acquire|
   #:|actionAt|
   #:|actionChanged|
   #:|actionGeometry|
   #:|actionGroup|
   #:|actionText|
   #:|actionTriggered|
   #:|actions|
   #:|action|
   #:|activateCurrentItem|
   #:|activateNextSubWindow|
   #:|activateNextWindow|
   #:|activatePreviousSubWindow|
   #:|activatePreviousWindow|
   #:|activateWindow|
   #:|activated(QModelIndex)|
   #:|activated(QString)|
   #:|activated(int)|
   #:|activatedAmbiguously|
   #:|activated|
   #:|activate|
   #:|activationOrder|
   #:|activeAction|
   #:|activeGestures|
   #:|activeModalWidget.QApplication|
   #:|activePanel|
   #:|activePopupWidget.QApplication|
   #:|activeStackChanged|
   #:|activeStack|
   #:|activeSubWindow|
   #:|activeWindow.QApplication|
   #:|activeWindow|
   #:|actualNumCopies|
   #:|actualSize|
   #:|addAction(QAction*)|
   #:|addAction(QIcon...)|
   #:|addAction(QString)|
   #:|addAction(QString...)|
   #:|addActions|
   #:|addAction|
   #:|addAnchors|
   #:|addAnchor|
   #:|addAnimation|
   #:|addApplicationFont.QFontDatabase|
   #:|addApplicationFontFromData.QFontDatabase|
   #:|addBindValue|
   #:|addButton(QAbstractButton*...)|
   #:|addButton(QString...)|
   #:|addButton|
   #:|addChildLayoutItem|
   #:|addChildren|
   #:|addChild|
   #:|addClass|
   #:|addControllingSignal|
   #:|addCornerAnchors|
   #:|addCustomFilter|
   #:|addDatabase(QSqlDriver*).QSqlDatabase|
   #:|addDatabase(QSqlDriver*...).QSqlDatabase|
   #:|addDatabase(QString).QSqlDatabase|
   #:|addDatabase(QString...).QSqlDatabase|
   #:|addDatabase.QSqlDatabase|
   #:|addData|
   #:|addDays|
   #:|addDefaultAnimation|
   #:|addDockWidget|
   #:|addEllipse|
   #:|addEncodedQueryItem|
   #:|addFile|
   #:|addHistoryEntry|
   #:|addItem(QIcon...)|
   #:|addItem(QListWidgetItem*)|
   #:|addItem(QString)|
   #:|addItem(QString...)|
   #:|addItems|
   #:|addItem|
   #:|addLayout|
   #:|addLibraryPath.QCoreApplication|
   #:|addLine|
   #:|addLocalScheme.QWebSecurityOrigin|
   #:|addMSecs|
   #:|addMapping|
   #:|addMenu(QMenu*)|
   #:|addMenu(QString)|
   #:|addMenu|
   #:|addMonths|
   #:|addPage|
   #:|addPaths|
   #:|addPath|
   #:|addPause|
   #:|addPermanentWidget|
   #:|addPixmap|
   #:|addPolygon|
   #:|addQueryItem|
   #:|addRect|
   #:|addRegion|
   #:|addResource|
   #:|addRoundedRect|
   #:|addRow(QLayout*)|
   #:|addRow(QString,QLayout*)|
   #:|addRow(QString,QWidget*)|
   #:|addRow(QString...)|
   #:|addRow(QWidget*)|
   #:|addRow(QWidget*,QLayout*)|
   #:|addRow(QWidget*,QWidget*)|
   #:|addRow(QWidget*...)|
   #:|addRow|
   #:|addScrollBarWidget|
   #:|addSearchPath.QDir|
   #:|addSecs|
   #:|addSeparator|
   #:|addShaderFromSourceCode(QGLShader::ShaderType,QByteArray)|
   #:|addShaderFromSourceCode(QGLShader::ShaderType,QString)|
   #:|addShaderFromSourceCode(QGLShader::ShaderType,const char*)|
   #:|addShaderFromSourceCode|
   #:|addShaderFromSourceFile|
   #:|addShader|
   #:|addSimpleText|
   #:|addSpacerItem|
   #:|addSpacing|
   #:|addStack|
   #:|addState|
   #:|addStep|
   #:|addStretch|
   #:|addStrut|
   #:|addSubWindow|
   #:|addTab|
   #:|addText|
   #:|addToGroup|
   #:|addToJavaScriptWindowObject|
   #:|addToolBar(QString)|
   #:|addToolBar(QToolBar*)|
   #:|addToolBarBreak|
   #:|addToolBar|
   #:|addTopLevelItems|
   #:|addTopLevelItem|
   #:|addTransition(QAbstractState*)|
   #:|addTransition(QAbstractTransition*)|
   #:|addTransition|
   #:|addWidget|
   #:|addWindow|
   #:|addYears|
   #:|added|
   #:|addressEntries|
   #:|addresses|
   #:|add|
   #:|adjoint|
   #:|adjustSize|
   #:|advance|
   #:|alert.QApplication|
   #:|algorithm|
   #:|aliases|
   #:|alignedRect.QStyle|
   #:|alignment|
   #:|allAddresses.QNetworkInterface|
   #:|allColumnsShowFocus|
   #:|allCookies|
   #:|allEncodedQueryItemValues|
   #:|allFormats|
   #:|allGray|
   #:|allInterfaces.QNetworkInterface|
   #:|allKeys|
   #:|allOrigins.QWebSecurityOrigin|
   #:|allQueryItemValues|
   #:|allWidgets.QApplication|
   #:|allowedAreasChanged|
   #:|allowedAreas|
   #:|allowsErrorInteraction|
   #:|allowsInteraction|
   #:|alphaBufferSize|
   #:|alphaF|
   #:|alpha|
   #:|alternateBase|
   #:|alternateSubjectNames|
   #:|alternateText|
   #:|alternatingRowColors|
   #:|amText|
   #:|amplitude|
   #:|anchorAt|
   #:|anchorClicked|
   #:|anchorHref|
   #:|anchorNames|
   #:|anchor|
   #:|angleAtPercent|
   #:|angleChanged|
   #:|angle|
   #:|animateClick|
   #:|animated|
   #:|animationAt|
   #:|animationCount|
   #:|animations|
   #:|answerRect|
   #:|appendColumns|
   #:|appendColumn|
   #:|appendHtml|
   #:|appendInside(QString)|
   #:|appendInside(QWebElement)|
   #:|appendInside|
   #:|appendOutside(QString)|
   #:|appendOutside(QWebElement)|
   #:|appendOutside|
   #:|appendPlainText|
   #:|appendRow(QList<QStandardItem*>)|
   #:|appendRow(QStandardItem*)|
   #:|appendRows|
   #:|appendRow|
   #:|appendUndoItem|
   #:|append|
   #:|applicationDirPath.QCoreApplication|
   #:|applicationFilePath.QCoreApplication|
   #:|applicationFontFamilies.QFontDatabase|
   #:|applicationName.QCoreApplication|
   #:|applicationName|
   #:|applicationPid.QCoreApplication|
   #:|applicationProxy.QNetworkProxy|
   #:|applicationVersion.QCoreApplication|
   #:|applyTo|
   #:|arcMoveTo|
   #:|arcTo|
   #:|areSharing.QGLContext|
   #:|arguments.QCoreApplication|
   #:|arrangeIcons|
   #:|arrowType|
   #:|ascent|
   #:|assignProperty|
   #:|associatedGraphicsWidgets|
   #:|associatedWidgets|
   #:|atBlockEnd|
   #:|atBlockStart|
   #:|atEnd|
   #:|atStart|
   #:|attachment|
   #:|attributeLocation(QByteArray)|
   #:|attributeLocation(QString)|
   #:|attributeLocation(const char*)|
   #:|attributeLocation|
   #:|attributeNS|
   #:|attributeNames|
   #:|attribute|
   #:|at|
   #:|authenticationMethod|
   #:|authenticationRequired|
   #:|authority|
   #:|autoBufferSwap|
   #:|autoClose|
   #:|autoDefault|
   #:|autoDelete|
   #:|autoExclusive|
   #:|autoExpandDelay|
   #:|autoFillBackground|
   #:|autoFormatting|
   #:|autoRaise|
   #:|autoRepeatDelay|
   #:|autoRepeatInterval|
   #:|autoRepeat|
   #:|autoReset|
   #:|autoSaveFilter|
   #:|autoScrollMargin|
   #:|autoSipEnabled|
   #:|availableCodecs.QTextCodec|
   #:|availableGeometry(QPoint)|
   #:|availableGeometry(const QWidget*)|
   #:|availableGeometry(int)|
   #:|availableGeometry|
   #:|availableMibs.QTextCodec|
   #:|availableRedoSteps|
   #:|availableSizes|
   #:|availableUndoSteps|
   #:|available|
   #:|averageCharWidth|
   #:|axisChanged|
   #:|axis|
   #:|backItems|
   #:|backItem|
   #:|backgroundBrush|
   #:|backgroundColor|
   #:|backgroundMode|
   #:|backgroundRole|
   #:|backgroundVisible|
   #:|background|
   #:|backspace|
   #:|backwardAvailable|
   #:|backwardHistoryCount|
   #:|backward|
   #:|back|
   #:|baseName|
   #:|baseSize|
   #:|baseUrl|
   #:|base|
   #:|batchSize|
   #:|beep.QApplication|
   #:|beforeDelete|
   #:|beforeInsert|
   #:|beforeUpdate|
   #:|before|
   #:|begin(QImage*)|
   #:|begin(QPicture*)|
   #:|begin(QPixmap*)|
   #:|begin(QPrinter*)|
   #:|begin(QWidget*)|
   #:|beginEditBlock|
   #:|beginGroup|
   #:|beginInsertColumns|
   #:|beginInsertRows|
   #:|beginLayout|
   #:|beginMacro|
   #:|beginMoveColumns|
   #:|beginMoveRows|
   #:|beginNativePainting|
   #:|beginReadArray|
   #:|beginRemoveColumns|
   #:|beginRemoveRows|
   #:|beginResetModel|
   #:|beginTransaction|
   #:|beginWriteArray|
   #:|begin|
   #:|bind(QHostAddress...)|
   #:|bind(quint16...)|
   #:|bindAttributeLocation(QByteArray...)|
   #:|bindAttributeLocation(QString...)|
   #:|bindAttributeLocation(const char*...)|
   #:|bindAttributeLocation|
   #:|bindTexture(QImage)|
   #:|bindTexture(QImage...)|
   #:|bindTexture(QPixmap)|
   #:|bindTexture(QPixmap...)|
   #:|bindTexture(QString)|
   #:|bindTexture|
   #:|bindToDynamicTexture|
   #:|bindValue(QString...)|
   #:|bindValue(int...)|
   #:|bindValueType(QString)|
   #:|bindValueType(int)|
   #:|bindValueType|
   #:|bindValue|
   #:|bindingSyntax|
   #:|bind|
   #:|bitmap|
   #:|blackF|
   #:|black|
   #:|blockBoundingGeometry|
   #:|blockBoundingRect|
   #:|blockCharFormat|
   #:|blockCountChanged|
   #:|blockCount|
   #:|blockFormatIndex|
   #:|blockFormat|
   #:|blockList|
   #:|blockNumber|
   #:|blockSignals|
   #:|block|
   #:|blueBufferSize|
   #:|blueF|
   #:|blue|
   #:|blurHintsChanged|
   #:|blurHints|
   #:|blurRadiusChanged|
   #:|blurRadius|
   #:|bold|
   #:|boolProperty|
   #:|borderBrush|
   #:|borderStyle|
   #:|border|
   #:|bottomMargin|
   #:|bottomPadding|
   #:|bottomRight|
   #:|bottomRow|
   #:|bottom|
   #:|boundValue(QString)|
   #:|boundValue(int)|
   #:|boundValueCount|
   #:|boundValueName|
   #:|boundValues|
   #:|boundValue|
   #:|boundaryReasons|
   #:|boundingRect(QChar)|
   #:|boundingRect(QRect...)|
   #:|boundingRect(QRectF,QString...)|
   #:|boundingRect(QRectF,int...)|
   #:|boundingRect(QRectF...)|
   #:|boundingRect(QString)|
   #:|boundingRectFor|
   #:|boundingRect|
   #:|boundingRegionGranularity|
   #:|boundingRegion|
   #:|boundsOnElement|
   #:|brightText|
   #:|broadcast|
   #:|brushOrigin|
   #:|brushProperty|
   #:|brush|
   #:|bspTreeDepth|
   #:|buddy|
   #:|buildDate.QLibraryInfo|
   #:|buildKey.QLibraryInfo|
   #:|bundleName|
   #:|buttonClicked(QAbstractButton*)|
   #:|buttonClicked(int)|
   #:|buttonClicked|
   #:|buttonDownPos|
   #:|buttonDownScenePos|
   #:|buttonDownScreenPos|
   #:|buttonPressed(QAbstractButton*)|
   #:|buttonPressed(int)|
   #:|buttonPressed|
   #:|buttonReleased(QAbstractButton*)|
   #:|buttonReleased(int)|
   #:|buttonReleased|
   #:|buttonRole|
   #:|buttonSymbols|
   #:|buttonText|
   #:|buttons|
   #:|button|
   #:|byteCount|
   #:|bytesAvailable|
   #:|bytesPerLine|
   #:|bytesReceived|
   #:|bytesToWrite|
   #:|bytesWritten|
   #:|c.QLocale|
   #:|caCertificates|
   #:|cacheDirectory|
   #:|cacheEnabled|
   #:|cacheKey|
   #:|cacheLimit.QPixmapCache|
   #:|cacheMode|
   #:|cacheSize|
   #:|cache|
   #:|caching|
   #:|calendarPopup|
   #:|calendarWidget|
   #:|canConvert|
   #:|canEncode(QChar)|
   #:|canEncode(QString)|
   #:|canEncode|
   #:|canFetchMore|
   #:|canGoBack|
   #:|canGoForward|
   #:|canPaste|
   #:|canReadLine|
   #:|canRedoChanged|
   #:|canRedo|
   #:|canUndoChanged|
   #:|canUndo|
   #:|cancelButtonText|
   #:|cancelDelayedEvent|
   #:|cancelIndexing|
   #:|cancelSearching|
   #:|canceledGestures|
   #:|canceled|
   #:|cancel|
   #:|canonicalFilePath|
   #:|canonicalPath|
   #:|capStyle|
   #:|capabilities|
   #:|capitalization|
   #:|captureCount|
   #:|capturedTexts|
   #:|cap|
   #:|cascadeSubWindows|
   #:|cascade|
   #:|cascadingSectionResizes|
   #:|caseSensitivity|
   #:|cdUp|
   #:|cd|
   #:|cellActivated|
   #:|cellAt(QTextCursor)|
   #:|cellAt(int)|
   #:|cellAt|
   #:|cellChanged|
   #:|cellClicked|
   #:|cellDoubleClicked|
   #:|cellEntered|
   #:|cellPadding|
   #:|cellPressed|
   #:|cellRect|
   #:|cellSpacing|
   #:|cellWidget|
   #:|centerButtons|
   #:|centerCursor|
   #:|centerOn(QPointF)|
   #:|centerOn(const QGraphicsItem*)|
   #:|centerOnScroll|
   #:|centerOn|
   #:|centerPoint|
   #:|center|
   #:|centralWidget|
   #:|certificate|
   #:|changeBrightness|
   #:|changeContrast|
   #:|changeFlags|
   #:|changeGamma|
   #:|changeInterval|
   #:|changeOverrideCursor.QApplication|
   #:|changePersistentIndexList|
   #:|changePersistentIndex|
   #:|changeSize|
   #:|changed|
   #:|charFormatIndex|
   #:|charFormat|
   #:|characterAt|
   #:|characterCount|
   #:|checkConnectArgs.QMetaObject|
   #:|checkOverflow(double)|
   #:|checkOverflow(int)|
   #:|checkOverflow|
   #:|checkState|
   #:|checkedAction|
   #:|checkedButton|
   #:|checkedId|
   #:|childAt|
   #:|childCount|
   #:|childFrames|
   #:|childGroups|
   #:|childIndicatorPolicy|
   #:|childItems|
   #:|childKeys|
   #:|childMode|
   #:|childPosition|
   #:|childrenBoundingRect|
   #:|childrenChanged|
   #:|childrenCollapsible|
   #:|childrenRect|
   #:|childrenRegion|
   #:|children|
   #:|child|
   #:|ciphers|
   #:|classInfoCount|
   #:|classInfoOffset|
   #:|className|
   #:|classes|
   #:|cleanChanged|
   #:|cleanIcon|
   #:|cleanIndex|
   #:|cleanPath.QDir|
   #:|cleanText|
   #:|cleanupPage|
   #:|clear.QPixmapCache|
   #:|clearAdditionalFormats|
   #:|clearBackground|
   #:|clearBit|
   #:|clearColumnWidthConstraints|
   #:|clearContents|
   #:|clearEditText|
   #:|clearError|
   #:|clearFocus|
   #:|clearForeground|
   #:|clearHistory|
   #:|clearIconDatabase.QWebSettings|
   #:|clearLayout|
   #:|clearMapping|
   #:|clearMask|
   #:|clearMaximumDateTime|
   #:|clearMaximumDate|
   #:|clearMaximumTime|
   #:|clearMemoryCaches.QWebSettings|
   #:|clearMessage|
   #:|clearMinimumDateTime|
   #:|clearMinimumDate|
   #:|clearMinimumTime|
   #:|clearPendingCommands|
   #:|clearPropertyFlags|
   #:|clearProperty|
   #:|clearSelection|
   #:|clearSpans|
   #:|clearValues|
   #:|clear|
   #:|clickedButton|
   #:|clicked|
   #:|click|
   #:|clipPath|
   #:|clipRegion|
   #:|clipboard.QApplication|
   #:|cloneDatabase.QSqlDatabase|
   #:|clone|
   #:|closeActiveSubWindow|
   #:|closeActiveWindow|
   #:|closeAllSubWindows|
   #:|closeAllWindows|
   #:|closeEditor|
   #:|closePersistentEditor|
   #:|closeReadChannel|
   #:|closeSubpath|
   #:|closeWriteChannel|
   #:|closestAcceptableSize.QLayout|
   #:|closestLegalPosition|
   #:|close|
   #:|closingDown.QCoreApplication|
   #:|codecForCStrings.QTextCodec|
   #:|codecForHtml.QTextCodec|
   #:|codecForLocale.QTextCodec|
   #:|codecForMib.QTextCodec|
   #:|codecForName(QByteArray).QTextCodec|
   #:|codecForName(const char*).QTextCodec|
   #:|codecForName.QTextCodec|
   #:|codecForTr.QTextCodec|
   #:|codecForUtfText.QTextCodec|
   #:|codec|
   #:|collapseAll|
   #:|collapseItem|
   #:|collapsed|
   #:|collapse|
   #:|collateCopies|
   #:|collectionFile|
   #:|collidesWithItem|
   #:|collidesWithPath|
   #:|collidingItems|
   #:|colorChanged|
   #:|colorCount|
   #:|colorData|
   #:|colorMode|
   #:|colorNames.QColor|
   #:|colorProperty|
   #:|colorSelected|
   #:|colorSpec.QApplication|
   #:|colorTable|
   #:|colormap|
   #:|color|
   #:|columnAlignment|
   #:|columnAt|
   #:|columnCountChanged|
   #:|columnCount|
   #:|columnIntersectsSelection|
   #:|columnMaximumWidth|
   #:|columnMinimumWidth|
   #:|columnMoved|
   #:|columnNumber|
   #:|columnPreferredWidth|
   #:|columnResized|
   #:|columnSpacing|
   #:|columnSpan|
   #:|columnStretchFactor|
   #:|columnStretch|
   #:|columnViewportPosition|
   #:|columnWidthConstraints|
   #:|columnWidths|
   #:|columnWidth|
   #:|columnsAboutToBeInserted|
   #:|columnsAboutToBeMoved|
   #:|columnsAboutToBeRemoved|
   #:|columnsInserted|
   #:|columnsMoved|
   #:|columnsRemoved|
   #:|columns|
   #:|column|
   #:|combinedLayoutSpacing|
   #:|combinedTransform|
   #:|comboBoxItems|
   #:|commandFinished|
   #:|commandStarted|
   #:|command|
   #:|commitDataRequest|
   #:|commitData|
   #:|commitString|
   #:|commitTransaction|
   #:|commit|
   #:|commonAncestorItem|
   #:|compileSourceCode(QByteArray)|
   #:|compileSourceCode(QString)|
   #:|compileSourceCode(const char*)|
   #:|compileSourceCode|
   #:|compileSourceFile|
   #:|completeBaseName|
   #:|completeChanged|
   #:|completeSuffix|
   #:|completer|
   #:|complete|
   #:|completionColumn|
   #:|completionCount|
   #:|completionModel|
   #:|completionMode|
   #:|completionPrefix|
   #:|completionRole|
   #:|compositionMode|
   #:|confirmOverwrite|
   #:|conjugate|
   #:|connect.QObject|
   #:|connectOptions|
   #:|connectPath|
   #:|connectSlotsByName.QMetaObject|
   #:|connectToHost(QHostAddress...)|
   #:|connectToHost(QString...)|
   #:|connectToHostImplementation|
   #:|connectToHost|
   #:|connectToServer|
   #:|connected|
   #:|connectionClosed|
   #:|connectionNames.QSqlDatabase|
   #:|connectionName|
   #:|connect|
   #:|constructorCount|
   #:|contains(QPainterPath)|
   #:|contains(QPoint)|
   #:|contains(QPointF)|
   #:|contains(QRect)|
   #:|contains(QRectF)|
   #:|contains.QSqlDatabase|
   #:|contains|
   #:|contentItemAt|
   #:|contentOffset|
   #:|contentsChanged|
   #:|contentsChange|
   #:|contentsCreated|
   #:|contentsCreationStarted|
   #:|contentsMargins|
   #:|contentsRect|
   #:|contentsSizeChanged|
   #:|contentsSize|
   #:|contextMenuPolicy|
   #:|contextMenu|
   #:|context|
   #:|controlPointRect|
   #:|controlTypes|
   #:|controlType|
   #:|convertToFormat(QImage::Format,QVector<QRgb>)|
   #:|convertToFormat(QImage::Format,Qt::ImageConversionFlags)|
   #:|convertToFormat|
   #:|convertToGLFormat.QGLWidget|
   #:|convertTo|
   #:|convert|
   #:|cookieJar|
   #:|cookiesForUrl|
   #:|coordinateMode|
   #:|copy.QFile|
   #:|copyAvailable|
   #:|copyCollectionFile|
   #:|copy|
   #:|cornerWidget|
   #:|corner|
   #:|correctionMode|
   #:|countryToString.QLocale|
   #:|country|
   #:|count|
   #:|createAction.QWhatsThis|
   #:|createAlphaMask|
   #:|createContents|
   #:|createEditor|
   #:|createHeuristicMask|
   #:|createIndex|
   #:|createItemGroup|
   #:|createLine|
   #:|createList(QTextListFormat)|
   #:|createList(QTextListFormat::Style)|
   #:|createList|
   #:|createMaskFromColor|
   #:|createPopupMenu|
   #:|createProxyForChildWidget|
   #:|createRedoAction|
   #:|createResult|
   #:|createStandardContextMenu|
   #:|createStroke|
   #:|createUndoAction|
   #:|createdWidgets|
   #:|created|
   #:|create|
   #:|creator|
   #:|critical.QMessageBox|
   #:|crossProduct.QVector3D|
   #:|cubicTo|
   #:|current.QDir|
   #:|currentAnimationChanged|
   #:|currentAnimation|
   #:|currentBlockState|
   #:|currentBlockUserData|
   #:|currentBlock|
   #:|currentCellChanged|
   #:|currentChanged(QWidget*)|
   #:|currentChanged(int)|
   #:|currentChanged|
   #:|currentCharFormatChanged|
   #:|currentCharFormat|
   #:|currentColorChanged|
   #:|currentColorGroup|
   #:|currentColor|
   #:|currentColumnChanged|
   #:|currentColumn|
   #:|currentCommand|
   #:|currentCompletion|
   #:|currentContext.QGLContext|
   #:|currentDate.QDate|
   #:|currentDateTime.QDateTime|
   #:|currentFilterChanged|
   #:|currentFilter|
   #:|currentFontChanged|
   #:|currentFont|
   #:|currentFrameNumber|
   #:|currentFrame|
   #:|currentIdChanged|
   #:|currentId|
   #:|currentImage|
   #:|currentIndexChanged(QString)|
   #:|currentIndexChanged(int)|
   #:|currentIndexChanged|
   #:|currentIndex|
   #:|currentItemChanged|
   #:|currentItemIndex|
   #:|currentItem|
   #:|currentList|
   #:|currentLoopChanged|
   #:|currentLoopTime|
   #:|currentLoop|
   #:|currentMessage|
   #:|currentPageChanged|
   #:|currentPage|
   #:|currentPath.QDir|
   #:|currentPixmap|
   #:|currentPosition|
   #:|currentRowChanged|
   #:|currentRow|
   #:|currentSectionIndex|
   #:|currentSection|
   #:|currentSubWindow|
   #:|currentTable|
   #:|currentTextChanged|
   #:|currentText|
   #:|currentTime.QTime|
   #:|currentTime|
   #:|currentValue|
   #:|currentWidget|
   #:|cursorBackward|
   #:|cursorFlashTime.QApplication|
   #:|cursorForPosition|
   #:|cursorForward|
   #:|cursorName|
   #:|cursorPositionAt|
   #:|cursorPositionChanged|
   #:|cursorPosition|
   #:|cursorRect|
   #:|cursorToX|
   #:|cursorWidth|
   #:|cursorWordBackward|
   #:|cursorWordForward|
   #:|cursor|
   #:|curveShape|
   #:|curveThreshold|
   #:|customButtonClicked|
   #:|customColor.QColorDialog|
   #:|customContextMenuRequested|
   #:|customCount.QColorDialog|
   #:|customFilters|
   #:|customValue|
   #:|cut|
   #:|cyanF|
   #:|cyan|
   #:|darker|
   #:|dark|
   #:|dashOffset|
   #:|dashPattern|
   #:|dataChanged|
   #:|dataTransferProgress|
   #:|database.QSqlDatabase|
   #:|databaseName|
   #:|databaseQuotaExceeded|
   #:|databaseQuota|
   #:|databaseText|
   #:|databaseUsage|
   #:|databases|
   #:|database|
   #:|data|
   #:|dateChanged|
   #:|dateEditAcceptDelay|
   #:|dateFormat|
   #:|dateTextFormat|
   #:|dateTimeChanged|
   #:|dateTimeFormat|
   #:|dateTime|
   #:|date|
   #:|dayName|
   #:|dayOfWeek|
   #:|dayOfYear|
   #:|daysInMonth|
   #:|daysInYear|
   #:|daysTo|
   #:|day|
   #:|decimalPoint|
   #:|decimals|
   #:|decodeName(QByteArray).QFile|
   #:|decodeName(const char*).QFile|
   #:|decodeName.QFile|
   #:|defaultAlignment|
   #:|defaultAnimations|
   #:|defaultButton|
   #:|defaultConfiguration.QSslConfiguration|
   #:|defaultDepth.QPixmap|
   #:|defaultDropAction|
   #:|defaultFactory.QItemEditorFactory|
   #:|defaultFamily|
   #:|defaultFont|
   #:|defaultFormat.QGLFormat|
   #:|defaultFormat.QSettings|
   #:|defaultInterface.QWebHistoryInterface|
   #:|defaultOverlayFormat.QGLFormat|
   #:|defaultSectionSize|
   #:|defaultSize|
   #:|defaultState|
   #:|defaultStyleSheet|
   #:|defaultSuffix|
   #:|defaultTextColor|
   #:|defaultTextEncoding|
   #:|defaultTextOption|
   #:|defaultValue|
   #:|defaultWidget|
   #:|delayedCloseFinished|
   #:|deleteChar|
   #:|deleteLater|
   #:|deletePreviousChar|
   #:|deleteResource|
   #:|deleteTexture|
   #:|delta|
   #:|del|
   #:|depthBufferSize|
   #:|depth|
   #:|descent|
   #:|description|
   #:|deselect|
   #:|desktop.QApplication|
   #:|desktopSettingsAware.QApplication|
   #:|destroyItemGroup|
   #:|destroyed|
   #:|destroy|
   #:|detach|
   #:|detailedText|
   #:|determinant|
   #:|deviceIsPixmap|
   #:|deviceTransform|
   #:|deviceType|
   #:|device|
   #:|dialMoved|
   #:|dialPressed|
   #:|dialReleased|
   #:|digest|
   #:|digitCount|
   #:|dirName|
   #:|directRendering|
   #:|directionChanged|
   #:|direction|
   #:|directories|
   #:|directoryChanged|
   #:|directoryEntered|
   #:|directoryLoaded|
   #:|directory|
   #:|dirtyRegionOffset|
   #:|dir|
   #:|disableAttributeArray(const char*)|
   #:|disableAttributeArray(int)|
   #:|disableAttributeArray|
   #:|discardCommand|
   #:|disconnect(const QObject*)|
   #:|disconnect(const QObject*...)|
   #:|disconnect(const char*)|
   #:|disconnect(const char*...)|
   #:|disconnect.QObject|
   #:|disconnectFromHostImplementation|
   #:|disconnectFromHost|
   #:|disconnectFromServer|
   #:|disconnected|
   #:|disconnect|
   #:|display(QString)|
   #:|display(double)|
   #:|display(int)|
   #:|displayColumn|
   #:|displayFormat|
   #:|displayName.QDesktopServices|
   #:|displayName|
   #:|displayText|
   #:|displayedSections|
   #:|display|
   #:|distanceToLine|
   #:|distanceToPlane|
   #:|doAction|
   #:|doItemsLayout|
   #:|docName|
   #:|dockLocationChanged|
   #:|dockOptions|
   #:|dockWidgetArea|
   #:|documentElement|
   #:|documentLayoutChanged|
   #:|documentLayout|
   #:|documentMargin|
   #:|documentMode|
   #:|documentSizeChanged|
   #:|documentSize|
   #:|documentTitle|
   #:|documentationFileName|
   #:|document|
   #:|domain|
   #:|doneCurrent|
   #:|done|
   #:|dotProduct.QVector2D|
   #:|dotProduct.QVector3D|
   #:|dotProduct.QVector4D|
   #:|dotsPerMeterX|
   #:|dotsPerMeterY|
   #:|doubleBuffer|
   #:|doubleClickInterval.QApplication|
   #:|doubleClicked|
   #:|doubleDecimals|
   #:|doubleMaximum|
   #:|doubleMinimum|
   #:|doubleProperty|
   #:|doubleSidedPrinting|
   #:|doubleValueChanged|
   #:|doubleValueSelected|
   #:|doubleValue|
   #:|downloadProgress|
   #:|downloadRequested|
   #:|dragDropMode|
   #:|dragDropOverwriteMode|
   #:|dragEnabled|
   #:|dragMode|
   #:|drawArc(QRect...)|
   #:|drawArc(QRectF...)|
   #:|drawArc|
   #:|drawBackground|
   #:|drawBase|
   #:|drawChord(QRect...)|
   #:|drawChord(QRectF...)|
   #:|drawChord|
   #:|drawComplexControl|
   #:|drawContents|
   #:|drawControl|
   #:|drawConvexPolygon(QPolygon)|
   #:|drawConvexPolygon(QPolygonF)|
   #:|drawConvexPolygon|
   #:|drawCursor|
   #:|drawEllipse(QPoint...)|
   #:|drawEllipse(QPointF...)|
   #:|drawEllipse(QRect)|
   #:|drawEllipse(QRectF)|
   #:|drawEllipse|
   #:|drawImage(QPoint...)|
   #:|drawImage(QPointF...)|
   #:|drawImage(QRect...)|
   #:|drawImage(QRectF...)|
   #:|drawImage(int...)|
   #:|drawImage|
   #:|drawItemPixmap|
   #:|drawItemText|
   #:|drawLine(QLine)|
   #:|drawLine(QLineF)|
   #:|drawLine(QPoint...)|
   #:|drawLine(QPointF...)|
   #:|drawLines(QVector<QLine>)|
   #:|drawLines(QVector<QLineF>)|
   #:|drawLines(QVector<QPoint>)|
   #:|drawLines(QVector<QPointF>)|
   #:|drawLines(const QLine*...)|
   #:|drawLines(const QLineF*...)|
   #:|drawLines(const QPointF*...)|
   #:|drawLines|
   #:|drawLine|
   #:|drawPath|
   #:|drawPicture(QPoint...)|
   #:|drawPicture(QPointF...)|
   #:|drawPicture|
   #:|drawPie(QRect...)|
   #:|drawPie(QRectF...)|
   #:|drawPie|
   #:|drawPixmap(QPoint...)|
   #:|drawPixmap(QPointF...)|
   #:|drawPixmap(QRect...)|
   #:|drawPixmap(QRectF...)|
   #:|drawPixmap(int...)|
   #:|drawPixmap|
   #:|drawPoint(QPoint)|
   #:|drawPoint(QPointF)|
   #:|drawPoints(QPolygon)|
   #:|drawPoints(QPolygonF)|
   #:|drawPoints|
   #:|drawPoint|
   #:|drawPolygon(QPolygon)|
   #:|drawPolygon(QPolygon...)|
   #:|drawPolygon(QPolygonF)|
   #:|drawPolygon(QPolygonF...)|
   #:|drawPolygon(const QPointF*...)|
   #:|drawPolygon|
   #:|drawPolyline(QPolygon)|
   #:|drawPolyline(QPolygonF)|
   #:|drawPolyline|
   #:|drawPrimitive|
   #:|drawRect(QRect)|
   #:|drawRect(QRectF)|
   #:|drawRects(QVector<QRect>)|
   #:|drawRects(QVector<QRectF>)|
   #:|drawRects(const QRect*...)|
   #:|drawRects(const QRectF*...)|
   #:|drawRects|
   #:|drawRect|
   #:|drawRoundedRect(QRect...)|
   #:|drawRoundedRect(QRectF...)|
   #:|drawRoundedRect|
   #:|drawSource|
   #:|drawText(QPoint...)|
   #:|drawText(QPointF...)|
   #:|drawText(QRect...)|
   #:|drawText(QRectF,QString...)|
   #:|drawText(QRectF,int...)|
   #:|drawText(QRectF...)|
   #:|drawText(int...)|
   #:|drawTexture(QPointF...)|
   #:|drawTexture(QRectF...)|
   #:|drawTexture|
   #:|drawText|
   #:|drawTiledPixmap(QRect...)|
   #:|drawTiledPixmap(QRectF...)|
   #:|drawTiledPixmap|
   #:|drawTree|
   #:|draw|
   #:|driverName|
   #:|driverText|
   #:|drivers.QSqlDatabase|
   #:|driver|
   #:|drives.QDir|
   #:|dropAction|
   #:|dropEvent|
   #:|dropIndicatorPosition|
   #:|dropMimeData|
   #:|dumpObjectInfo|
   #:|dumpObjectTree|
   #:|duplex|
   #:|duplicatesEnabled|
   #:|duration|
   #:|dx|
   #:|dynamicPropertyNames|
   #:|dynamicSortFilter|
   #:|dy|
   #:|easingCurve|
   #:|echoMode|
   #:|editItem|
   #:|editStrategy|
   #:|editTextChanged|
   #:|editTriggers|
   #:|editingFinished|
   #:|editorDestroyed|
   #:|editorEvent|
   #:|edit|
   #:|effectiveDate|
   #:|effectiveOpacity|
   #:|effectiveSizeHint|
   #:|effectiveWinId|
   #:|elapsed|
   #:|elementCount|
   #:|elementExists|
   #:|elementId|
   #:|element|
   #:|elideMode|
   #:|elidedText|
   #:|emitDataChanged|
   #:|emitSelectionChanged|
   #:|emptyLabel|
   #:|enableAttributeArray(const char*)|
   #:|enableAttributeArray(int)|
   #:|enableAttributeArray|
   #:|enablePersistentStorage.QWebSettings|
   #:|enabledChanged|
   #:|encloseContentsWith(QString)|
   #:|encloseContentsWith(QWebElement)|
   #:|encloseContentsWith|
   #:|encloseWith(QString)|
   #:|encloseWith(QWebElement)|
   #:|encloseWith|
   #:|enclosingBlockElement|
   #:|encodeName.QFile|
   #:|encodedData|
   #:|encodedFragment|
   #:|encodedHost|
   #:|encodedPassword|
   #:|encodedPath|
   #:|encodedQueryItemValue|
   #:|encodedQuery|
   #:|encodedUserName|))

(in-package :eql)

(pushnew :qt-wrapper-functions *features*)

(defun %auto-cast (object)
  (when (find (qt-object-id (ensure-qt-object object))
              '#.(list (qid "QGraphicsSvgItem")
                       (qid "QGraphicsTextItem")
                       (qid "QGraphicsWidget")))
    "QGraphicsItem"))
