(defpackage :eql
  (:export
   #:|abort|
   #:|about.QMessageBox|
   #:|aboutQt.QMessageBox|
   #:|aboutQt|
   #:|aboutToActivate|
   #:|aboutToClose|
   #:|aboutToHide|
   #:|aboutToQuit|
   #:|aboutToShow|
   #:|absoluteDir|
   #:|absoluteFilePath|
   #:|absolutePath|
   #:|acceleration|
   #:|accept(QGesture*)|
   #:|accept(Qt::GestureType)|
   #:|acceptDrops|
   #:|acceptHoverEvents|
   #:|acceptMode|
   #:|acceptProposedAction|
   #:|acceptRichText|
   #:|acceptTouchEvents|
   #:|acceptedMouseButtons|
   #:|accepted|
   #:|accept|
   #:|accessibleDescription|
   #:|accessibleName|
   #:|accessibleText|
   #:|acquire|
   #:|actionAt|
   #:|actionChanged|
   #:|actionGeometry|
   #:|actionGroup|
   #:|actionText|
   #:|actionTriggered|
   #:|actions|
   #:|action|
   #:|activateNextSubWindow|
   #:|activateNextWindow|
   #:|activatePreviousSubWindow|
   #:|activatePreviousWindow|
   #:|activateWindow|
   #:|activated(QModelIndex)|
   #:|activated(QString)|
   #:|activated(int)|
   #:|activatedAmbiguously|
   #:|activated|
   #:|activate|
   #:|activationOrder|
   #:|activeAction|
   #:|activeGestures|
   #:|activeModalWidget.QApplication|
   #:|activePanel|
   #:|activePopupWidget.QApplication|
   #:|activeStackChanged|
   #:|activeStack|
   #:|activeSubWindow|
   #:|activeWindow.QApplication|
   #:|activeWindow|
   #:|actualNumCopies|
   #:|actualSize|
   #:|addAction(QAction*)|
   #:|addAction(QIcon...)|
   #:|addAction(QString)|
   #:|addAction(QString...)|
   #:|addActions|
   #:|addAction|
   #:|addAnchors|
   #:|addAnchor|
   #:|addAnimation|
   #:|addApplicationFont.QFontDatabase|
   #:|addApplicationFontFromData.QFontDatabase|
   #:|addButton(QAbstractButton*...)|
   #:|addButton(QString...)|
   #:|addButton|
   #:|addChildLayoutItem|
   #:|addChildren|
   #:|addChild|
   #:|addControllingSignal|
   #:|addCornerAnchors|
   #:|addData|
   #:|addDays|
   #:|addDefaultAnimation|
   #:|addDockWidget|
   #:|addEllipse|
   #:|addEncodedQueryItem|
   #:|addFile|
   #:|addItem(QIcon...)|
   #:|addItem(QListWidgetItem*)|
   #:|addItem(QString)|
   #:|addItem(QString...)|
   #:|addItems|
   #:|addItem|
   #:|addLayout|
   #:|addLibraryPath.QCoreApplication|
   #:|addLine|
   #:|addMSecs|
   #:|addMapping|
   #:|addMenu(QMenu*)|
   #:|addMenu(QString)|
   #:|addMenu|
   #:|addMonths|
   #:|addPage|
   #:|addPaths|
   #:|addPath|
   #:|addPause|
   #:|addPermanentWidget|
   #:|addPixmap|
   #:|addPolygon|
   #:|addQueryItem|
   #:|addRect|
   #:|addRegion|
   #:|addResource|
   #:|addRoundedRect|
   #:|addRow(QLayout*)|
   #:|addRow(QString,QLayout*)|
   #:|addRow(QString,QWidget*)|
   #:|addRow(QString...)|
   #:|addRow(QWidget*)|
   #:|addRow(QWidget*,QLayout*)|
   #:|addRow(QWidget*,QWidget*)|
   #:|addRow(QWidget*...)|
   #:|addRow|
   #:|addScrollBarWidget|
   #:|addSearchPath.QDir|
   #:|addSecs|
   #:|addSeparator|
   #:|addSimpleText|
   #:|addSpacerItem|
   #:|addSpacing|
   #:|addStack|
   #:|addState|
   #:|addStep|
   #:|addStretch|
   #:|addStrut|
   #:|addSubWindow|
   #:|addTab|
   #:|addText|
   #:|addToGroup|
   #:|addToolBar(QString)|
   #:|addToolBar(QToolBar*)|
   #:|addToolBarBreak|
   #:|addToolBar|
   #:|addTopLevelItems|
   #:|addTopLevelItem|
   #:|addTransition(QAbstractState*)|
   #:|addTransition(QAbstractTransition*)|
   #:|addTransition|
   #:|addWidget|
   #:|addWindow|
   #:|addYears|
   #:|added|
   #:|add|
   #:|adjoint|
   #:|adjustSize|
   #:|advance|
   #:|alert.QApplication|
   #:|aliases|
   #:|alignedRect.QStyle|
   #:|alignment|
   #:|allColumnsShowFocus|
   #:|allEncodedQueryItemValues|
   #:|allFormats|
   #:|allGray|
   #:|allKeys|
   #:|allQueryItemValues|
   #:|allWidgets.QApplication|
   #:|allowedAreasChanged|
   #:|allowedAreas|
   #:|allowsErrorInteraction|
   #:|allowsInteraction|
   #:|alphaF|
   #:|alpha|
   #:|alternateBase|
   #:|alternatingRowColors|
   #:|amText|
   #:|amplitude|
   #:|anchorAt|
   #:|anchorClicked|
   #:|anchorHref|
   #:|anchorNames|
   #:|anchor|
   #:|angleAtPercent|
   #:|angleChanged|
   #:|angle|
   #:|animateClick|
   #:|animationAt|
   #:|animationCount|
   #:|animations|
   #:|answerRect|
   #:|appendColumns|
   #:|appendColumn|
   #:|appendHtml|
   #:|appendPlainText|
   #:|appendRow(QList<QStandardItem*>)|
   #:|appendRow(QStandardItem*)|
   #:|appendRows|
   #:|appendRow|
   #:|appendUndoItem|
   #:|append|
   #:|applicationDirPath.QCoreApplication|
   #:|applicationFilePath.QCoreApplication|
   #:|applicationFontFamilies.QFontDatabase|
   #:|applicationName.QCoreApplication|
   #:|applicationName|
   #:|applicationPid.QCoreApplication|
   #:|applicationVersion.QCoreApplication|
   #:|applyTo|
   #:|arcMoveTo|
   #:|arcTo|
   #:|arguments.QCoreApplication|
   #:|arrangeIcons|
   #:|arrowType|
   #:|ascent|
   #:|assignProperty|
   #:|associatedGraphicsWidgets|
   #:|associatedWidgets|
   #:|atBlockEnd|
   #:|atBlockStart|
   #:|atEnd|
   #:|atStart|
   #:|at|
   #:|authority|
   #:|autoClose|
   #:|autoDefault|
   #:|autoDelete|
   #:|autoExclusive|
   #:|autoExpandDelay|
   #:|autoFillBackground|
   #:|autoFormatting|
   #:|autoRaise|
   #:|autoRepeatDelay|
   #:|autoRepeatInterval|
   #:|autoRepeat|
   #:|autoReset|
   #:|autoScrollMargin|
   #:|autoSipEnabled|
   #:|availableCodecs.QTextCodec|
   #:|availableGeometry(QPoint)|
   #:|availableGeometry(const QWidget*)|
   #:|availableGeometry(int)|
   #:|availableGeometry|
   #:|availableMibs.QTextCodec|
   #:|availableRedoSteps|
   #:|availableSizes|
   #:|availableUndoSteps|
   #:|available|
   #:|averageCharWidth|
   #:|axisChanged|
   #:|axis|
   #:|backgroundBrush|
   #:|backgroundColor|
   #:|backgroundMode|
   #:|backgroundRole|
   #:|backgroundVisible|
   #:|background|
   #:|backspace|
   #:|backwardAvailable|
   #:|backwardHistoryCount|
   #:|backward|
   #:|back|
   #:|baseName|
   #:|baseSize|
   #:|base|
   #:|batchSize|
   #:|beep.QApplication|
   #:|before|
   #:|begin(QImage*)|
   #:|begin(QPicture*)|
   #:|begin(QPixmap*)|
   #:|begin(QPrinter*)|
   #:|begin(QWidget*)|
   #:|beginEditBlock|
   #:|beginGroup|
   #:|beginInsertColumns|
   #:|beginInsertRows|
   #:|beginLayout|
   #:|beginMacro|
   #:|beginMoveColumns|
   #:|beginMoveRows|
   #:|beginNativePainting|
   #:|beginReadArray|
   #:|beginRemoveColumns|
   #:|beginRemoveRows|
   #:|beginResetModel|
   #:|beginWriteArray|
   #:|begin|
   #:|bitmap|
   #:|blackF|
   #:|black|
   #:|blockBoundingGeometry|
   #:|blockBoundingRect|
   #:|blockCharFormat|
   #:|blockCountChanged|
   #:|blockCount|
   #:|blockFormatIndex|
   #:|blockFormat|
   #:|blockList|
   #:|blockNumber|
   #:|blockSignals|
   #:|block|
   #:|blueF|
   #:|blue|
   #:|blurHintsChanged|
   #:|blurHints|
   #:|blurRadiusChanged|
   #:|blurRadius|
   #:|bold|
   #:|boolProperty|
   #:|borderBrush|
   #:|borderStyle|
   #:|border|
   #:|bottomMargin|
   #:|bottomPadding|
   #:|bottomRight|
   #:|bottomRow|
   #:|bottom|
   #:|boundaryReasons|
   #:|boundingRect(QChar)|
   #:|boundingRect(QRect...)|
   #:|boundingRect(QRectF,QString...)|
   #:|boundingRect(QRectF,int...)|
   #:|boundingRect(QRectF...)|
   #:|boundingRect(QString)|
   #:|boundingRectFor|
   #:|boundingRect|
   #:|boundingRegionGranularity|
   #:|boundingRegion|
   #:|brightText|
   #:|brushOrigin|
   #:|brushProperty|
   #:|brush|
   #:|bspTreeDepth|
   #:|buddy|
   #:|buffer|
   #:|buildDate.QLibraryInfo|
   #:|buildKey.QLibraryInfo|
   #:|bundleName|
   #:|buttonClicked(QAbstractButton*)|
   #:|buttonClicked(int)|
   #:|buttonClicked|
   #:|buttonDownPos|
   #:|buttonDownScenePos|
   #:|buttonDownScreenPos|
   #:|buttonPressed(QAbstractButton*)|
   #:|buttonPressed(int)|
   #:|buttonPressed|
   #:|buttonReleased(QAbstractButton*)|
   #:|buttonReleased(int)|
   #:|buttonReleased|
   #:|buttonRole|
   #:|buttonSymbols|
   #:|buttonText|
   #:|buttons|
   #:|button|
   #:|byteCount|
   #:|bytesAvailable|
   #:|bytesPerLine|
   #:|bytesToWrite|
   #:|bytesWritten|
   #:|c.QLocale|
   #:|cacheEnabled|
   #:|cacheKey|
   #:|cacheLimit.QPixmapCache|
   #:|cacheMode|
   #:|caching|
   #:|calendarPopup|
   #:|calendarWidget|
   #:|canConvert|
   #:|canEncode(QChar)|
   #:|canEncode(QString)|
   #:|canEncode|
   #:|canFetchMore|
   #:|canPaste|
   #:|canReadLine|
   #:|canRedoChanged|
   #:|canRedo|
   #:|canUndoChanged|
   #:|canUndo|
   #:|cancelButtonText|
   #:|cancelDelayedEvent|
   #:|canceledGestures|
   #:|canceled|
   #:|cancel|
   #:|canonicalFilePath|
   #:|canonicalPath|
   #:|capStyle|
   #:|capitalization|
   #:|captureCount|
   #:|capturedTexts|
   #:|cap|
   #:|cascadeSubWindows|
   #:|cascade|
   #:|cascadingSectionResizes|
   #:|caseSensitivity|
   #:|cdUp|
   #:|cd|
   #:|cellActivated|
   #:|cellAt(QTextCursor)|
   #:|cellAt(int)|
   #:|cellAt|
   #:|cellChanged|
   #:|cellClicked|
   #:|cellDoubleClicked|
   #:|cellEntered|
   #:|cellPadding|
   #:|cellPressed|
   #:|cellRect|
   #:|cellSpacing|
   #:|cellWidget|
   #:|centerButtons|
   #:|centerCursor|
   #:|centerOn(QPointF)|
   #:|centerOn(const QGraphicsItem*)|
   #:|centerOnScroll|
   #:|centerOn|
   #:|centerPoint|
   #:|center|
   #:|centralWidget|
   #:|changeBrightness|
   #:|changeContrast|
   #:|changeFlags|
   #:|changeGamma|
   #:|changeInterval|
   #:|changeOverrideCursor.QApplication|
   #:|changePersistentIndexList|
   #:|changePersistentIndex|
   #:|changeSize|
   #:|changed|
   #:|charFormatIndex|
   #:|charFormat|
   #:|characterAt|
   #:|characterCount|
   #:|checkConnectArgs.QMetaObject|
   #:|checkOverflow(double)|
   #:|checkOverflow(int)|
   #:|checkOverflow|
   #:|checkState|
   #:|checkedAction|
   #:|checkedButton|
   #:|checkedId|
   #:|childAt|
   #:|childCount|
   #:|childFrames|
   #:|childGroups|
   #:|childIndicatorPolicy|
   #:|childItems|
   #:|childKeys|
   #:|childMode|
   #:|childrenBoundingRect|
   #:|childrenChanged|
   #:|childrenCollapsible|
   #:|childrenRect|
   #:|childrenRegion|
   #:|children|
   #:|child|
   #:|classInfoCount|
   #:|classInfoOffset|
   #:|className|
   #:|cleanChanged|
   #:|cleanIcon|
   #:|cleanIndex|
   #:|cleanPath.QDir|
   #:|cleanText|
   #:|cleanupPage|
   #:|clear.QPixmapCache|
   #:|clearAdditionalFormats|
   #:|clearBackground|
   #:|clearBit|
   #:|clearColumnWidthConstraints|
   #:|clearContents|
   #:|clearEditText|
   #:|clearError|
   #:|clearFocus|
   #:|clearForeground|
   #:|clearHistory|
   #:|clearLayout|
   #:|clearMapping|
   #:|clearMask|
   #:|clearMaximumDateTime|
   #:|clearMaximumDate|
   #:|clearMaximumTime|
   #:|clearMessage|
   #:|clearMinimumDateTime|
   #:|clearMinimumDate|
   #:|clearMinimumTime|
   #:|clearPropertyFlags|
   #:|clearProperty|
   #:|clearSelection|
   #:|clearSpans|
   #:|clear|
   #:|clickedButton|
   #:|clicked|
   #:|click|
   #:|clipPath|
   #:|clipRegion|
   #:|clipboard.QApplication|
   #:|clone|
   #:|closeActiveSubWindow|
   #:|closeActiveWindow|
   #:|closeAllSubWindows|
   #:|closeAllWindows|
   #:|closeEditor|
   #:|closePersistentEditor|
   #:|closeReadChannel|
   #:|closeSubpath|
   #:|closeWriteChannel|
   #:|closestAcceptableSize.QLayout|
   #:|closestLegalPosition|
   #:|close|
   #:|closingDown.QCoreApplication|
   #:|codecForCStrings.QTextCodec|
   #:|codecForHtml.QTextCodec|
   #:|codecForLocale.QTextCodec|
   #:|codecForMib.QTextCodec|
   #:|codecForName(QByteArray).QTextCodec|
   #:|codecForName(const char*).QTextCodec|
   #:|codecForName.QTextCodec|
   #:|codecForTr.QTextCodec|
   #:|codecForUtfText.QTextCodec|
   #:|codec|
   #:|collapseAll|
   #:|collapseItem|
   #:|collapsed|
   #:|collapse|
   #:|collateCopies|
   #:|collidesWithItem|
   #:|collidesWithPath|
   #:|collidingItems|
   #:|colorChanged|
   #:|colorCount|
   #:|colorData|
   #:|colorMode|
   #:|colorNames.QColor|
   #:|colorProperty|
   #:|colorSelected|
   #:|colorSpec.QApplication|
   #:|colorTable|
   #:|color|
   #:|columnAlignment|
   #:|columnAt|
   #:|columnCountChanged|
   #:|columnCount|
   #:|columnIntersectsSelection|
   #:|columnMaximumWidth|
   #:|columnMinimumWidth|
   #:|columnMoved|
   #:|columnNumber|
   #:|columnPreferredWidth|
   #:|columnResized|
   #:|columnSpacing|
   #:|columnSpan|
   #:|columnStretchFactor|
   #:|columnStretch|
   #:|columnViewportPosition|
   #:|columnWidthConstraints|
   #:|columnWidths|
   #:|columnWidth|
   #:|columnsAboutToBeInserted|
   #:|columnsAboutToBeMoved|
   #:|columnsAboutToBeRemoved|
   #:|columnsInserted|
   #:|columnsMoved|
   #:|columnsRemoved|
   #:|columns|
   #:|column|
   #:|combinedLayoutSpacing|
   #:|combinedTransform|
   #:|comboBoxItems|
   #:|command|
   #:|commitDataRequest|
   #:|commitData|
   #:|commitString|
   #:|commonAncestorItem|
   #:|completeBaseName|
   #:|completeChanged|
   #:|completeSuffix|
   #:|completer|
   #:|complete|
   #:|completionColumn|
   #:|completionCount|
   #:|completionModel|
   #:|completionMode|
   #:|completionPrefix|
   #:|completionRole|
   #:|compositionMode|
   #:|confirmOverwrite|
   #:|conjugate|
   #:|connect.QObject|
   #:|connectPath|
   #:|connectSlotsByName.QMetaObject|
   #:|connect|
   #:|constructorCount|
   #:|contains(QPainterPath)|
   #:|contains(QPoint)|
   #:|contains(QPointF)|
   #:|contains(QRect)|
   #:|contains(QRectF)|
   #:|contains|
   #:|contentOffset|
   #:|contentsChanged|
   #:|contentsChange|
   #:|contentsMargins|
   #:|contentsRect|
   #:|contextMenuPolicy|
   #:|contextMenu|
   #:|context|
   #:|controlPointRect|
   #:|controlTypes|
   #:|controlType|
   #:|convertToFormat(QImage::Format,QVector<QRgb>)|
   #:|convertToFormat(QImage::Format,Qt::ImageConversionFlags)|
   #:|convertToFormat|
   #:|convertTo|
   #:|convert|
   #:|coordinateMode|
   #:|copy.QFile|
   #:|copyAvailable|
   #:|copy|
   #:|cornerWidget|
   #:|corner|
   #:|correctionMode|
   #:|countryToString.QLocale|
   #:|country|
   #:|count|
   #:|createAction.QWhatsThis|
   #:|createAlphaMask|
   #:|createEditor|
   #:|createHeuristicMask|
   #:|createItemGroup|
   #:|createLine|
   #:|createList(QTextListFormat)|
   #:|createList(QTextListFormat::Style)|
   #:|createList|
   #:|createMaskFromColor|
   #:|createPopupMenu|
   #:|createProxyForChildWidget|
   #:|createRedoAction|
   #:|createStandardContextMenu|
   #:|createStroke|
   #:|createUndoAction|
   #:|createdWidgets|
   #:|created|
   #:|creator|
   #:|critical.QMessageBox|
   #:|crossProduct.QVector3D|
   #:|cubicTo|
   #:|current.QDir|
   #:|currentAnimationChanged|
   #:|currentAnimation|
   #:|currentBlockState|
   #:|currentBlockUserData|
   #:|currentBlock|
   #:|currentCellChanged|
   #:|currentChanged(QWidget*)|
   #:|currentChanged(int)|
   #:|currentChanged|
   #:|currentCharFormatChanged|
   #:|currentCharFormat|
   #:|currentColorChanged|
   #:|currentColorGroup|
   #:|currentColor|
   #:|currentColumnChanged|
   #:|currentColumn|
   #:|currentCompletion|
   #:|currentDate.QDate|
   #:|currentDateTime.QDateTime|
   #:|currentFontChanged|
   #:|currentFont|
   #:|currentFrameNumber|
   #:|currentFrame|
   #:|currentIdChanged|
   #:|currentId|
   #:|currentImage|
   #:|currentIndexChanged(QString)|
   #:|currentIndexChanged(int)|
   #:|currentIndexChanged|
   #:|currentIndex|
   #:|currentItemChanged|
   #:|currentItem|
   #:|currentList|
   #:|currentLoopChanged|
   #:|currentLoopTime|
   #:|currentLoop|
   #:|currentMessage|
   #:|currentPageChanged|
   #:|currentPage|
   #:|currentPath.QDir|
   #:|currentPixmap|
   #:|currentPosition|
   #:|currentRowChanged|
   #:|currentRow|
   #:|currentSectionIndex|
   #:|currentSection|
   #:|currentSubWindow|
   #:|currentTable|
   #:|currentTextChanged|
   #:|currentText|
   #:|currentTime.QTime|
   #:|currentTime|
   #:|currentValue|
   #:|currentWidget|
   #:|cursorBackward|
   #:|cursorFlashTime.QApplication|
   #:|cursorForPosition|
   #:|cursorForward|
   #:|cursorPositionAt|
   #:|cursorPositionChanged|
   #:|cursorPosition|
   #:|cursorRect|
   #:|cursorToX|
   #:|cursorWidth|
   #:|cursorWordBackward|
   #:|cursorWordForward|
   #:|cursor|
   #:|curveShape|
   #:|curveThreshold|
   #:|customButtonClicked|
   #:|customColor.QColorDialog|
   #:|customContextMenuRequested|
   #:|customCount.QColorDialog|
   #:|cut|
   #:|cyanF|
   #:|cyan|
   #:|darker|
   #:|dark|
   #:|dashOffset|
   #:|dashPattern|
   #:|dataChanged|
   #:|data|
   #:|dateChanged|
   #:|dateEditAcceptDelay|
   #:|dateFormat|
   #:|dateTextFormat|
   #:|dateTimeChanged|
   #:|dateTimeFormat|
   #:|dateTime|
   #:|date|
   #:|dayName|
   #:|dayOfWeek|
   #:|dayOfYear|
   #:|daysInMonth|
   #:|daysInYear|
   #:|daysTo|
   #:|day|
   #:|decimalPoint|
   #:|decimals|
   #:|decodeName(QByteArray).QFile|
   #:|decodeName(const char*).QFile|
   #:|decodeName.QFile|
   #:|defaultAlignment|
   #:|defaultAnimations|
   #:|defaultButton|
   #:|defaultDepth.QPixmap|
   #:|defaultDropAction|
   #:|defaultFactory.QItemEditorFactory|
   #:|defaultFamily|
   #:|defaultFont|
   #:|defaultFormat.QSettings|
   #:|defaultSectionSize|
   #:|defaultState|
   #:|defaultStyleSheet|
   #:|defaultSuffix|
   #:|defaultTextColor|
   #:|defaultTextOption|
   #:|defaultWidget|
   #:|deleteChar|
   #:|deleteLater|
   #:|deletePreviousChar|
   #:|delta|
   #:|del|
   #:|depth|
   #:|descent|
   #:|description|
   #:|deselect|
   #:|desktop.QApplication|
   #:|desktopSettingsAware.QApplication|
   #:|destroyItemGroup|
   #:|destroyed|
   #:|destroy|
   #:|detach|
   #:|detailedText|
   #:|determinant|
   #:|deviceTransform|
   #:|deviceType|
   #:|device|
   #:|dialMoved|
   #:|dialPressed|
   #:|dialReleased|
   #:|digitCount|
   #:|dirName|
   #:|directionChanged|
   #:|direction|
   #:|directories|
   #:|directoryChanged|
   #:|directoryEntered|
   #:|directoryLoaded|
   #:|directory|
   #:|dirtyRegionOffset|
   #:|dir|
   #:|discardCommand|
   #:|disconnect(const QObject*)|
   #:|disconnect(const QObject*...)|
   #:|disconnect(const char*)|
   #:|disconnect(const char*...)|
   #:|disconnect.QObject|
   #:|disconnect|
   #:|display(QString)|
   #:|display(double)|
   #:|display(int)|
   #:|displayFormat|
   #:|displayName.QDesktopServices|
   #:|displayText|
   #:|displayedSections|
   #:|display|
   #:|distanceToLine|
   #:|distanceToPlane|
   #:|doAction|
   #:|doItemsLayout|
   #:|docName|
   #:|dockLocationChanged|
   #:|dockOptions|
   #:|dockWidgetArea|
   #:|documentLayoutChanged|
   #:|documentLayout|
   #:|documentMargin|
   #:|documentMode|
   #:|documentSizeChanged|
   #:|documentSize|
   #:|documentTitle|
   #:|document|
   #:|done|
   #:|dotProduct.QVector2D|
   #:|dotProduct.QVector3D|
   #:|dotProduct.QVector4D|
   #:|dotsPerMeterX|
   #:|dotsPerMeterY|
   #:|doubleClickInterval.QApplication|
   #:|doubleClicked|
   #:|doubleDecimals|
   #:|doubleMaximum|
   #:|doubleMinimum|
   #:|doubleProperty|
   #:|doubleSidedPrinting|
   #:|doubleValueChanged|
   #:|doubleValueSelected|
   #:|doubleValue|
   #:|dragDropMode|
   #:|dragDropOverwriteMode|
   #:|dragEnabled|
   #:|dragMode|
   #:|drawArc(QRect...)|
   #:|drawArc(QRectF...)|
   #:|drawArc|
   #:|drawBackground|
   #:|drawBase|
   #:|drawChord(QRect...)|
   #:|drawChord(QRectF...)|
   #:|drawChord|
   #:|drawComplexControl|
   #:|drawContents|
   #:|drawControl|
   #:|drawConvexPolygon(QPolygon)|
   #:|drawConvexPolygon(QPolygonF)|
   #:|drawConvexPolygon|
   #:|drawCursor|
   #:|drawEllipse(QPoint...)|
   #:|drawEllipse(QPointF...)|
   #:|drawEllipse(QRect)|
   #:|drawEllipse(QRectF)|
   #:|drawEllipse|
   #:|drawImage(QPoint...)|
   #:|drawImage(QPointF...)|
   #:|drawImage(QRect...)|
   #:|drawImage(QRectF...)|
   #:|drawImage(int...)|
   #:|drawImage|
   #:|drawItemPixmap|
   #:|drawItemText|
   #:|drawLine(QLine)|
   #:|drawLine(QLineF)|
   #:|drawLine(QPoint...)|
   #:|drawLine(QPointF...)|
   #:|drawLines(QVector<QLine>)|
   #:|drawLines(QVector<QLineF>)|
   #:|drawLines(QVector<QPoint>)|
   #:|drawLines(QVector<QPointF>)|
   #:|drawLines(const QLine*...)|
   #:|drawLines(const QLineF*...)|
   #:|drawLines(const QPointF*...)|
   #:|drawLines|
   #:|drawLine|
   #:|drawPath|
   #:|drawPicture(QPoint...)|
   #:|drawPicture(QPointF...)|
   #:|drawPicture|
   #:|drawPie(QRect...)|
   #:|drawPie(QRectF...)|
   #:|drawPie|
   #:|drawPixmap(QPoint...)|
   #:|drawPixmap(QPointF...)|
   #:|drawPixmap(QRect...)|
   #:|drawPixmap(QRectF...)|
   #:|drawPixmap(int...)|
   #:|drawPixmap|
   #:|drawPoint(QPoint)|
   #:|drawPoint(QPointF)|
   #:|drawPoints(QPolygon)|
   #:|drawPoints(QPolygonF)|
   #:|drawPoints|
   #:|drawPoint|
   #:|drawPolygon(QPolygon)|
   #:|drawPolygon(QPolygon...)|
   #:|drawPolygon(QPolygonF)|
   #:|drawPolygon(QPolygonF...)|
   #:|drawPolygon(const QPointF*...)|
   #:|drawPolygon|
   #:|drawPolyline(QPolygon)|
   #:|drawPolyline(QPolygonF)|
   #:|drawPolyline|
   #:|drawPrimitive|
   #:|drawRect(QRect)|
   #:|drawRect(QRectF)|
   #:|drawRects(QVector<QRect>)|
   #:|drawRects(QVector<QRectF>)|
   #:|drawRects(const QRect*...)|
   #:|drawRects(const QRectF*...)|
   #:|drawRects|
   #:|drawRect|
   #:|drawRoundedRect(QRect...)|
   #:|drawRoundedRect(QRectF...)|
   #:|drawRoundedRect|
   #:|drawSource|
   #:|drawText(QPoint...)|
   #:|drawText(QPointF...)|
   #:|drawText(QRect...)|
   #:|drawText(QRectF,QString...)|
   #:|drawText(QRectF,int...)|
   #:|drawText(QRectF...)|
   #:|drawText(int...)|
   #:|drawText|
   #:|drawTiledPixmap(QRect...)|
   #:|drawTiledPixmap(QRectF...)|
   #:|drawTiledPixmap|
   #:|drawTree|
   #:|draw|
   #:|drives.QDir|
   #:|dropAction|
   #:|dropEvent|
   #:|dropIndicatorPosition|
   #:|dropMimeData|
   #:|dumpObjectInfo|
   #:|dumpObjectTree|
   #:|duplex|
   #:|duplicatesEnabled|
   #:|duration|
   #:|dx|
   #:|dynamicPropertyNames|
   #:|dynamicSortFilter|
   #:|dy|
   #:|easingCurve|
   #:|echoMode|
   #:|editItem|
   #:|editTextChanged|
   #:|editTriggers|
   #:|editingFinished|
   #:|editorDestroyed|
   #:|editorEvent|
   #:|edit|
   #:|effectiveOpacity|
   #:|effectiveSizeHint|
   #:|elapsed|
   #:|elementCount|
   #:|elideMode|
   #:|elidedText|
   #:|emitDataChanged|
   #:|emitSelectionChanged|
   #:|emptyLabel|
   #:|enabledChanged|
   #:|encodeName.QFile|
   #:|encodedData|
   #:|encodedFragment|
   #:|encodedHost|
   #:|encodedPassword|
   #:|encodedPath|
   #:|encodedQueryItemValue|
   #:|encodedQuery|
   #:|encodedUserName|
   #:|endArray|
   #:|endEditBlock|
   #:|endFrame|
   #:|endGroup|
   #:|endInsertColumns|
   #:|endInsertRows|
   #:|endLayout|
   #:|endMacro|
   #:|endMoveColumns|
   #:|endMoveRows|
   #:|endNativePainting|
   #:|endRemoveColumns|
   #:|endRemoveRows|
   #:|endResetModel|
   #:|endValue|
   #:|end|
   #:|ensureBlockLayout|
   #:|ensureCursorVisible|
   #:|ensurePolished|
   #:|ensureVisible(QRectF)|
   #:|ensureVisible(QRectF...)|
   #:|ensureVisible(const QGraphicsItem*)|
   #:|ensureVisible(const QGraphicsItem*...)|
   #:|ensureVisible|
   #:|ensureWidgetVisible|
   #:|enterWhatsThisMode.QWhatsThis|
   #:|entered|
   #:|entryInfoList(QDir::Filters)|
   #:|entryInfoList(QDir::Filters...)|
   #:|entryInfoList(QStringList)|
   #:|entryInfoList(QStringList...)|
   #:|entryInfoList|
   #:|entryList(QDir::Filters)|
   #:|entryList(QDir::Filters...)|
   #:|entryList(QStringList)|
   #:|entryList(QStringList...)|
   #:|entryList|
   #:|enumeratorCount|
   #:|enumeratorOffset|
   #:|eraseRect(QRect)|
   #:|eraseRect(QRectF)|
   #:|eraseRect|
   #:|errorState|
   #:|errorString|
   #:|error|
   #:|escape.QRegExp|
   #:|escapeButton|
   #:|eventFilter|
   #:|eventSource|
   #:|eventType|
   #:|event|
   #:|exactMatch|
   #:|exclusive|
   #:|exec.QApplication|
   #:|exec.QCoreApplication|
   #:|exec.QMenu|
   #:|execute.QProcess|
   #:|executeDelayedItemsLayout|
   #:|exec|
   #:|exists.QFile|
   #:|exists|
   #:|exit.QCoreApplication|
   #:|exitCode|
   #:|exitStatus|
   #:|exited|
   #:|exit|
   #:|expandAll|
   #:|expandItem|
   #:|expandToDepth|
   #:|expanded|
   #:|expandingDirections|
   #:|expanding|
   #:|expandsOnDoubleClick|
   #:|expand|
   #:|exponential|
   #:|extraSelections|
   #:|fallbacksEnabled|
   #:|families|
   #:|family|
   #:|featuresChanged|
   #:|features|
   #:|fetchMore|
   #:|fieldGrowthPolicy|
   #:|field|
   #:|fileChanged|
   #:|fileIcon|
   #:|fileInfo|
   #:|fileMode|
   #:|fileName|
   #:|filePath|
   #:|fileRenamed|
   #:|fileSelected|
   #:|filesSelected|
   #:|files|
   #:|file|
   #:|fillPath|
   #:|fillRect(QRect,QBrush)|
   #:|fillRect(QRect,QColor)|
   #:|fillRect(QRect,Qt::BrushStyle)|
   #:|fillRect(QRect,Qt::GlobalColor)|
   #:|fillRect(QRect...)|
   #:|fillRect(QRectF,QBrush)|
   #:|fillRect(QRectF,QColor)|
   #:|fillRect(QRectF,Qt::BrushStyle)|
   #:|fillRect(QRectF,Qt::GlobalColor)|
   #:|fillRect(QRectF...)|
   #:|fillRect(int,int,int,int,QBrush)|
   #:|fillRect(int,int,int,int,QColor)|
   #:|fillRect(int,int,int,int,Qt::BrushStyle)|
   #:|fillRect(int,int,int,int,Qt::GlobalColor)|
   #:|fillRect|
   #:|fillRule|
   #:|fill|
   #:|filterCaseSensitivity|
   #:|filterEvent|
   #:|filterKeyColumn|
   #:|filterRegExp|
   #:|filterRole|
   #:|filterSelected|
   #:|filtersChildEvents|
   #:|filter|
   #:|finalStop|
   #:|find(QRegExp)|
   #:|find(QRegExp,QTextCursor)|
   #:|find(QRegExp,QTextCursor...)|
   #:|find(QRegExp,int)|
   #:|find(QRegExp,int...)|
   #:|find(QRegExp...)|
   #:|find(QString)|
   #:|find(QString,QTextCursor)|
   #:|find(QString,QTextCursor...)|
   #:|find(QString,int)|
   #:|find(QString,int...)|
   #:|find(QString...)|
   #:|find.QPixmapCache|
   #:|findBlockByLineNumber|
   #:|findBlockByNumber|
   #:|findBlock|
   #:|findBufferChanged|
   #:|findData|
   #:|findItems|
   #:|findText|
   #:|find|
   #:|finished|
   #:|finish|
   #:|firstBlock|
   #:|firstCursorPosition|
   #:|firstDayOfWeek|
   #:|firstLineNumber|
   #:|firstPosition|
   #:|firstVisibleBlock|
   #:|fitInView(QRectF)|
   #:|fitInView(QRectF...)|
   #:|fitInView(const QGraphicsItem*)|
   #:|fitInView(const QGraphicsItem*...)|
   #:|fitInView|
   #:|fitToWidth|
   #:|fixedPitch|
   #:|fixup|
   #:|flags|
   #:|flipCoordinates|
   #:|flow|
   #:|flush.QCoreApplication|
   #:|flush|
   #:|focalPoint|
   #:|focusChanged|
   #:|focusItem|
   #:|focusNextChild|
   #:|focusNextPrevChild|
   #:|focusPolicy|
   #:|focusPreviousChild|
   #:|focusProxy|
   #:|focusWidget.QApplication|
   #:|focusWidget|
   #:|font(const QWidget*).QApplication|
   #:|font(const char*).QApplication|
   #:|font.QApplication|
   #:|font.QToolTip|
   #:|fontCapitalization|
   #:|fontDatabaseChanged|
   #:|fontEmbeddingEnabled|
   #:|fontFamily|
   #:|fontFilters|
   #:|fontFixedPitch|
   #:|fontInfo|
   #:|fontItalic|
   #:|fontKerning|
   #:|fontLetterSpacing|
   #:|fontMetrics.QApplication|
   #:|fontMetrics|
   #:|fontOverline|
   #:|fontPointSize|
   #:|fontSelected|
   #:|fontStrikeOut|
   #:|fontStyleHint|
   #:|fontStyleStrategy|
   #:|fontUnderline|
   #:|fontWeight|
   #:|fontWordSpacing|
   #:|font|
   #:|forceShow|
   #:|foregroundBrush|
   #:|foregroundRole|
   #:|foreground|
   #:|formAlignment|
   #:|formatIndex|
   #:|formats|
   #:|format|
   #:|forwardAvailable|
   #:|forwardHistoryCount|
   #:|forward|
   #:|fragment|
   #:|frameBoundingRect|))

(in-package :eql)

(defun %auto-cast (object)
  (when (find (qt-object-id object) '#.(list (qid "QGraphicsSvgItem") (qid "QGraphicsTextItem") (qid"QGraphicsWidget")))
    "QGraphicsItem"))
