(defpackage :eql
  (:export
   #:|setFile(QString)|
   #:|setFileMode|
   #:|setFileNameAndVersion(QString,QString)|
   #:|setFileNameAndVersion(QString,int)|
   #:|setFileName|
   #:|setFile|
   #:|setFillRule|
   #:|setFilterCaseSensitivity|
   #:|setFilterFixedString|
   #:|setFilterKeyColumn|
   #:|setFilterRegExp(QRegExp)|
   #:|setFilterRegExp(QString)|
   #:|setFilterRegExp|
   #:|setFilterRole|
   #:|setFilterWildcard|
   #:|setFiltersChildEvents|
   #:|setFilter|
   #:|setFinalPage|
   #:|setFinalStop|
   #:|setFirstColumnSpanned|
   #:|setFirstDayOfWeek|
   #:|setFirstItemColumnSpanned|
   #:|setFixedHeight|
   #:|setFixedPitch|
   #:|setFixedSize|
   #:|setFixedWidth|
   #:|setFlags|
   #:|setFlag|
   #:|setFlat|
   #:|setFloatable|
   #:|setFloating|
   #:|setFlow|
   #:|setFocalPoint|
   #:|setFocusItem|
   #:|setFocusPolicy|
   #:|setFocusProxy|
   #:|setFocusWidget|
   #:|setFocus|
   #:|setFont.QApplication|
   #:|setFont.QToolTip|
   #:|setFontCapitalization|
   #:|setFontEmbeddingEnabled|
   #:|setFontFamily|
   #:|setFontFilters|
   #:|setFontFixedPitch|
   #:|setFontItalic|
   #:|setFontKerning|
   #:|setFontLetterSpacing|
   #:|setFontOverline|
   #:|setFontPointSize|
   #:|setFontSize|
   #:|setFontStrikeOut|
   #:|setFontStyleHint|
   #:|setFontStyleStrategy|
   #:|setFontUnderline|
   #:|setFontWeight|
   #:|setFontWordSpacing|
   #:|setFont|
   #:|setForegroundBrush|
   #:|setForegroundRole|
   #:|setForeground|
   #:|setFormAlignment|
   #:|setFormat(int,int,QColor)|
   #:|setFormat(int,int,QFont)|
   #:|setFormat(int,int,QTextCharFormat)|
   #:|setFormat|
   #:|setForwardOnly|
   #:|setForwardUnsupportedContent|
   #:|setFragment|
   #:|setFrameFormat|
   #:|setFrameRange|
   #:|setFrameRect|
   #:|setFrameShadow|
   #:|setFrameShape|
   #:|setFrameStyle|
   #:|setFramesPerSecond|
   #:|setFrame|
   #:|setFromTo|
   #:|setFullPage|
   #:|setGenerated(QString...)|
   #:|setGenerated(int...)|
   #:|setGenerated|
   #:|setGeometry|
   #:|setGestureCancelPolicy|
   #:|setGlobalRestorePolicy|
   #:|setGlobalStrut.QApplication|
   #:|setGraphicsEffect|
   #:|setGraphicsItem|
   #:|setGraphicsSystem.QApplication|
   #:|setGreenBufferSize|
   #:|setGreenF|
   #:|setGreen|
   #:|setGridSize|
   #:|setGridStyle|
   #:|setGridVisible|
   #:|setGroup|
   #:|setHMS|
   #:|setHeaderData|
   #:|setHeaderHidden|
   #:|setHeaderItem|
   #:|setHeaderLabels|
   #:|setHeaderLabel|
   #:|setHeaderRowCount|
   #:|setHeaderTextFormat|
   #:|setHeader|
   #:|setHeight(QTextLength)|
   #:|setHeight(qreal)|
   #:|setHeightForWidth|
   #:|setHeight|
   #:|setHelp|
   #:|setHexMode|
   #:|setHidden|
   #:|setHighlightSections|
   #:|setHistoryType|
   #:|setHistory|
   #:|setHitTestPath|
   #:|setHorizontalHeaderFormat|
   #:|setHorizontalHeaderItem|
   #:|setHorizontalHeaderLabels|
   #:|setHorizontalHeader|
   #:|setHorizontalPolicy|
   #:|setHorizontalScrollBarPolicy|
   #:|setHorizontalScrollBar|
   #:|setHorizontalScrollMode|
   #:|setHorizontalSpacing|
   #:|setHorizontalStretch|
   #:|setHostName|
   #:|setHost|
   #:|setHotSpot|
   #:|setHslF|
   #:|setHsl|
   #:|setHsvF|
   #:|setHsv|
   #:|setHtml|
   #:|setHttpOnly|
   #:|setIconDatabasePath.QWebSettings|
   #:|setIconPixmap|
   #:|setIconProvider|
   #:|setIconSize|
   #:|setIconText|
   #:|setIconVisibleInMenu|
   #:|setIcon|
   #:|setIdnWhitelist.QUrl|
   #:|setId|
   #:|setImageData|
   #:|setImage|
   #:|setIndentWidth|
   #:|setIndentation|
   #:|setIndent|
   #:|setIndexWidget|
   #:|setIndex|
   #:|setInformativeText|
   #:|setIniCodec(QTextCodec*)|
   #:|setIniCodec(const char*)|
   #:|setIniCodec|
   #:|setInitialState|
   #:|setInitialized|
   #:|setInnerXml|
   #:|setInputContext|
   #:|setInputMask|
   #:|setInputMethodHints|
   #:|setInputMode|
   #:|setInsertPolicy|
   #:|setIntMaximum|
   #:|setIntMinimum|
   #:|setIntRange|
   #:|setIntStep|
   #:|setIntValue|
   #:|setInteractive|
   #:|setInternalTextureFormat|
   #:|setInterval|
   #:|setInvertedAppearance|
   #:|setInvertedControls|
   #:|setIp|
   #:|setItalic|
   #:|setItemData|
   #:|setItemDelegateForColumn|
   #:|setItemDelegateForRow|
   #:|setItemDelegate|
   #:|setItemEditorFactory|
   #:|setItemEnabled|
   #:|setItemIcon|
   #:|setItemIndexMethod|
   #:|setItemPrototype|
   #:|setItemSpacing|
   #:|setItemText|
   #:|setItemToolTip|
   #:|setItemWidget|
   #:|setItemsExpandable|
   #:|setItem|
   #:|setJoinStyle|
   #:|setKerning|
   #:|setKeyboardInputInterval.QApplication|
   #:|setKeyboardPageStep|
   #:|setKeyboardSingleStep|
   #:|setKeyboardTracking|
   #:|setKey|
   #:|setLabelAlignment|
   #:|setLabelText|
   #:|setLabel|
   #:|setLandscapeOrientation|
   #:|setLastCenterPoint|
   #:|setLastError|
   #:|setLastModified|
   #:|setLastOffset|
   #:|setLastRead|
   #:|setLastRotationAngle|
   #:|setLastScaleFactor|
   #:|setLayoutDirection.QApplication|
   #:|setLayoutDirection|
   #:|setLayoutMode|
   #:|setLayout|
   #:|setLazyChildCount|
   #:|setLeadingIncluded|
   #:|setLeftMargin|
   #:|setLeftPadding|
   #:|setLeft|
   #:|setLength|
   #:|setLetterSpacing|
   #:|setLibraryPaths.QCoreApplication|
   #:|setLineCount|
   #:|setLineEdit|
   #:|setLineWidth|
   #:|setLineWrapColumnOrWidth|
   #:|setLineWrapMode|
   #:|setLine|
   #:|setLinkDelegationPolicy|
   #:|setLoadHints|
   #:|setLocalAddress|
   #:|setLocalCertificate|
   #:|setLocalPort|
   #:|setLocalStoragePath|
   #:|setLocale|
   #:|setLookupId|
   #:|setLoopCount|
   #:|setLoops|
   #:|setManagerProperty(QString,QString)|
   #:|setManagerProperty(QString,QStringList)|
   #:|setMargin|
   #:|setMask(QBitmap)|
   #:|setMask(QRegion)|
   #:|setMask|
   #:|setMatrix|
   #:|setMaxCount|
   #:|setMaxLength|
   #:|setMaxPendingConnections|
   #:|setMaxVisibleItems|
   #:|setMaximumBlockCount|
   #:|setMaximumCacheSize|
   #:|setMaximumDateTime|
   #:|setMaximumDate|
   #:|setMaximumHeight|
   #:|setMaximumItemCount|
   #:|setMaximumPagesInCache.QWebSettings|
   #:|setMaximumSize|
   #:|setMaximumTime|
   #:|setMaximumWidth|
   #:|setMaximum|
   #:|setMenuBar|
   #:|setMenuRole|
   #:|setMenuWidget|
   #:|setMenu|
   #:|setMetaInformation|
   #:|setMidLineWidth|
   #:|setMimeData|
   #:|setMinMax|
   #:|setMinimal|
   #:|setMinimumContentsLength|
   #:|setMinimumDateTime|
   #:|setMinimumDate|
   #:|setMinimumDuration|
   #:|setMinimumHeight|
   #:|setMinimumSectionSize|
   #:|setMinimumSize|
   #:|setMinimumTime|
   #:|setMinimumWidth|
   #:|setMinimum|
   #:|setMiterLimit|
   #:|setModal|
   #:|setModelColumn|
   #:|setModelData|
   #:|setModelSorting|
   #:|setModel|
   #:|setMode|
   #:|setModified|
   #:|setModifierMask|
   #:|setMouseTracking|
   #:|setMovable|
   #:|setMovement|
   #:|setMovie|
   #:|setNameFilterDetailsVisible|
   #:|setNameFilterDisables|
   #:|setNameFilters|
   #:|setNameFilter|
   #:|setNamedColor|
   #:|setName|
   #:|setNativeMenuBar|
   #:|setNavigationBarVisible|
   #:|setNetmask|
   #:|setNetworkAccessManager|
   #:|setNonBreakableLines|
   #:|setNotation|
   #:|setNotchTarget|
   #:|setNotchesVisible|
   #:|setNull(QString)|
   #:|setNull(int)|
   #:|setNull|
   #:|setNum(double)|
   #:|setNum(int)|
   #:|setNumColumns|
   #:|setNumCopies|
   #:|setNumberOptions|
   #:|setNumber|
   #:|setNumericalPrecisionPolicy|
   #:|setNum|
   #:|setObjectCacheCapacities.QWebSettings|
   #:|setObjectIndex|
   #:|setObjectName|
   #:|setObjectType|
   #:|setOctMode|
   #:|setOfflineStorageDefaultQuota.QWebSettings|
   #:|setOfflineStoragePath.QWebSettings|
   #:|setOfflineWebApplicationCachePath.QWebSettings|
   #:|setOfflineWebApplicationCacheQuota.QWebSettings|
   #:|setOffset(QPointF)|
   #:|setOffset(qreal)|
   #:|setOffsetToLastSection|
   #:|setOffsetToSectionPosition|
   #:|setOffset|
   #:|setOkButtonText|
   #:|setOn|
   #:|setOpacityMask|
   #:|setOpacity|
   #:|setOpaqueResize|
   #:|setOpenExternalLinks|
   #:|setOpenLinks|
   #:|setOpenMode|
   #:|setOptimizationFlags|
   #:|setOptimizationFlag|
   #:|setOptionTabs|
   #:|setOptions|
   #:|setOption|
   #:|setOrganizationDomain.QCoreApplication|
   #:|setOrganizationName.QCoreApplication|
   #:|setOrientation|
   #:|setOriginCorner|
   #:|setOriginatingObject|
   #:|setOrigin|
   #:|setOuterXml|
   #:|setOutputFileName|
   #:|setOutputFormat|
   #:|setOverlay|
   #:|setOverline|
   #:|setOverrideCursor.QApplication|
   #:|setOvershoot|
   #:|setOverwriteMode|
   #:|setOwnedByLayout|
   #:|setOwner|
   #:|setPadding|
   #:|setPageBreakPolicy|
   #:|setPageMargins|
   #:|setPageOrder|
   #:|setPageSize|
   #:|setPageStep|
   #:|setPage|
   #:|setPaintDevice|
   #:|setPalette.QApplication|
   #:|setPalette.QToolTip|
   #:|setPalette|
   #:|setPanelModality|
   #:|setPaperSize|
   #:|setPaperSource|
   #:|setParentItem|
   #:|setParentLayoutItem|
   #:|setParent|
   #:|setPassword|
   #:|setPath.QSettings|
   #:|setPath|
   #:|setPatternSyntax|
   #:|setPattern|
   #:|setPaused|
   #:|setPeerAddress|
   #:|setPeerHostName|
   #:|setPeerName|
   #:|setPeerPort|
   #:|setPeerVerifyDepth|
   #:|setPeerVerifyMode|
   #:|setPen(QColor)|
   #:|setPen(QPen)|
   #:|setPen(Qt::PenStyle)|
   #:|setPen|
   #:|setPeriod|
   #:|setPermissions.QFile|
   #:|setPermissions|
   #:|setPicture|
   #:|setPixelSize|
   #:|setPixel|
   #:|setPixmap|
   #:|setPlainText|
   #:|setPlane|
   #:|setPluginFactory|
   #:|setPointSizeF|
   #:|setPointSize|
   #:|setPolygon|
   #:|setPopupMode|
   #:|setPopup|
   #:|setPortraitOrientation|
   #:|setPort|
   #:|setPos.QCursor|
   #:|setPositionForIndex|
   #:|setPosition|
   #:|setPos|
   #:|setPrecision|
   #:|setPreeditArea|
   #:|setPreferredContentsSize|
   #:|setPreferredHeight|
   #:|setPreferredSize|
   #:|setPreferredWidth|
   #:|setPrefixLength|
   #:|setPrefix|
   #:|setPreviewWidget|
   #:|setPrimaryKey|
   #:|setPrintProgram|
   #:|setPrintRange|
   #:|setPrinterName|
   #:|setPriority|
   #:|setPrivateKey|
   #:|setProcessChannelMode|
   #:|setProcessEnvironment|
   #:|setProcessState|
   #:|setProperty(int,QVariant)|
   #:|setProperty(int,QVector<QTextLength>)|
   #:|setPropertyName|
   #:|setProperty|
   #:|setProtocolTag|
   #:|setProtocol|
   #:|setProxyFactory|
   #:|setProxyModel|
   #:|setProxy|
   #:|setQuery(QSqlQuery)|
   #:|setQuery(QString)|
   #:|setQueryDelimiters|
   #:|setQueryType|
   #:|setQuery|
   #:|setQuitOnLastWindowClosed.QApplication|
   #:|setRadius|
   #:|setRangeSelected|
   #:|setRange|
   #:|setRawHeader|
   #:|setRawMode|
   #:|setRawName|
   #:|setReadBufferSize|
   #:|setReadChannel|
   #:|setReadOnly|
   #:|setReadable|
   #:|setRecord|
   #:|setRects|
   #:|setRect|
   #:|setRedBufferSize|
   #:|setRedF|
   #:|setRed|
   #:|setRegExp|
   #:|setRelation|
   #:|setRenderHints|
   #:|setRenderHint|
   #:|setRepeatAction|
   #:|setRequiredStatus|
   #:|setRequired|
   #:|setResizeAnchor|
   #:|setResizeGripsVisible|
   #:|setResizeMode|
   #:|setResolution|
   #:|setResolveSymlinks|
   #:|setRestartCommand|
   #:|setRestartHint|
   #:|setResult|
   #:|setRevision|
   #:|setRgbF|
   #:|setRgba|
   #:|setRgb|
   #:|setRightMargin|
   #:|setRightPadding|
   #:|setRight|
   #:|setRootIndex|
   #:|setRootIsDecorated|
   #:|setRootModelIndex|
   #:|setRootObject.QAccessible|
   #:|setRootPath|
   #:|setRotationAngle|
   #:|setRotation|
   #:|setRowAlignment|
   #:|setRowCount|
   #:|setRowFixedHeight|
   #:|setRowHeight|
   #:|setRowHidden|
   #:|setRowMaximumHeight|
   #:|setRowMinimumHeight|
   #:|setRowPreferredHeight|
   #:|setRowSpacing|
   #:|setRowStretchFactor|
   #:|setRowStretch|
   #:|setRowWrapPolicy|
   #:|setRow|
   #:|setRubberBandSelectionMode|
   #:|setRubberBand|
   #:|setSampleBuffers|
   #:|setSamples|
   #:|setSaveToDisk|
   #:|setScalar|
   #:|setScaleFactor|
   #:|setScaledContents|
   #:|setScaledSize|
   #:|setScale|
   #:|setSceneRect|
   #:|setScene|
   #:|setScheme|
   #:|setScopeId|
   #:|setScrollBarPolicy|
   #:|setScrollBarValue|
   #:|setScrollBarsEnabled|
   #:|setScrollPosition|
   #:|setSearchPaths.QDir|
   #:|setSearchPaths|
   #:|setSectionHidden|
   #:|setSecure|
   #:|setSegmentStyle|
   #:|setSelectable|
   #:|setSelectedDate|
   #:|setSelectedSection|
   #:|setSelected|
   #:|setSelectionArea|
   #:|setSelectionBehaviorOnRemove|
   #:|setSelectionBehavior|
   #:|setSelectionModel|
   #:|setSelectionMode|
   #:|setSelectionRectVisible|
   #:|setSelection|
   #:|setSenderObject|
   #:|setSeparatorsCollapsible|
   #:|setSeparator|
   #:|setShapeMode|
   #:|setShape|
   #:|setSharedRenderer|
   #:|setShortcutAutoRepeat|
   #:|setShortcutContext|
   #:|setShortcutEnabled|
   #:|setShortcuts(QKeySequence::StandardKey)|
   #:|setShortcuts(QList<QKeySequence>)|
   #:|setShortcuts|
   #:|setShortcut|
   #:|setShowGrid|
   #:|setShown|
   #:|setSidebarUrls|
   #:|setSignal|
   #:|setSinglePageViewMode|
   #:|setSingleShot|
   #:|setSingleStep|
   #:|setSizeAdjustPolicy|
   #:|setSizeConstraint|
   #:|setSizeGripEnabled|
   #:|setSizeHint|
   #:|setSizeIncrement|
   #:|setSizePolicy|
   #:|setSizes|
   #:|setSize|
   #:|setSliderDown|
   #:|setSliderPosition|
   #:|setSmallDecimalPoint|
   #:|setSocketDescriptor|
   #:|setSocketError|
   #:|setSocketOption|
   #:|setSocketState|
   #:|setSoftKeyRole|
   #:|setSortCacheEnabled|
   #:|setSortCaseSensitivity|
   #:|setSortIndicatorShown|
   #:|setSortIndicator|
   #:|setSortLocaleAware|
   #:|setSortRole|
   #:|setSortingEnabled|
   #:|setSorting|
   #:|setSort|
   #:|setSourceModel|
   #:|setSource|
   #:|setSpacing|
   #:|setSpanAngle|
   #:|setSpan|
   #:|setSpecialValueText|
   #:|setSpeed|
   #:|setSpread|
   #:|setSslConfiguration|
   #:|setStackingMode|
   #:|setStack|
   #:|setStandardButtons|
   #:|setStandardColor.QColorDialog|
   #:|setStandardErrorFile|
   #:|setStandardInputFile|
   #:|setStandardOutputFile|
   #:|setStandardOutputProcess|
   #:|setStartAngle|
   #:|setStartCenterPoint|
   #:|setStartDragDistance.QApplication|
   #:|setStartDragTime.QApplication|
   #:|setStartFrame|
   #:|setStartId|
   #:|setStartValue|
   #:|setStart|
   #:|setState|
   #:|setStatusBar|
   #:|setStatusTip|
   #:|setStencilBufferSize|
   #:|setStencil|
   #:|setStereo|
   #:|setStickyFocus|
   #:|setStops|
   #:|setStrength|
   #:|setStretchFactor(QLayout*...)|
   #:|setStretchFactor(QWidget*...)|
   #:|setStretchFactor|
   #:|setStretchLastSection|
   #:|setStretch|
   #:|setStrikeOut|
   #:|setStringList|
   #:|setStyle(QString).QApplication|
   #:|setStyle(QStyle*).QApplication|
   #:|setStyle.QApplication|
   #:|setStyleHint|
   #:|setStyleProperty|
   #:|setStyleSheet|
   #:|setStyleStrategy|
   #:|setStyle|
   #:|setSubTitleFormat|
   #:|setSubTitle|
   #:|setSubmitPolicy|
   #:|setSuffix|
   #:|setSupportedDragActions|
   #:|setSwapInterval|
   #:|setSwipeAngle|
   #:|setSymLink|
   #:|setSystemMenu|
   #:|setTabArray|
   #:|setTabBar|
   #:|setTabButton|
   #:|setTabChangesFocus|
   #:|setTabData|
   #:|setTabEnabled|
   #:|setTabIcon|
   #:|setTabKeyNavigation|
   #:|setTabOrder.QGraphicsWidget|
   #:|setTabOrder.QWidget|
   #:|setTabPositions|
   #:|setTabPosition|
   #:|setTabShape|
   #:|setTabStopWidth|
   #:|setTabStop|
   #:|setTabTextColor|
   #:|setTabText|
   #:|setTabToolTip|
   #:|setTabWhatsThis|
   #:|setTable|
   #:|setTabsClosable|
   #:|setTargetObject|
   #:|setTargetStates|
   #:|setTargetState|
   #:|setTearOffEnabled|
   #:|setTextAlignment|
   #:|setTextBackgroundColor|
   #:|setTextColor|
   #:|setTextCursor|
   #:|setTextDirection|
   #:|setTextEchoMode|
   #:|setTextElideMode|
   #:|setTextFormat|
   #:|setTextIndent|
   #:|setTextInteractionFlags|
   #:|setTextMargins|
   #:|setTextModeEnabled|
   #:|setTextOption|
   #:|setTextOutline|
   #:|setTextPosition|
   #:|setTextSizeMultiplier|
   #:|setTextValue|
   #:|setTextVisible|
   #:|setTextWidth|
   #:|setTextureCacheLimit.QGLContext|
   #:|setTextureImage|
   #:|setTextureTarget|
   #:|setTexture|
   #:|setText|
   #:|setThemeName.QIcon|
   #:|setThemeSearchPaths.QIcon|
   #:|setTickInterval|
   #:|setTickPosition|
   #:|setTimeRange|
   #:|setTimeSpec|
   #:|setTime_t|
   #:|setTime|
   #:|setTitleBarWidget|
   #:|setTitleFormat|
   #:|setTitle|
   #:|setToIdentity|
   #:|setToolButtonStyle|
   #:|setToolTip|
   #:|setTopMargin|
   #:|setTopPadding|
   #:|setTop|
   #:|setTotalChangeFlags|
   #:|setTotalRotationAngle|
   #:|setTotalScaleFactor|
   #:|setTracking|
   #:|setTransferMode|
   #:|setTransformOriginPoint|
   #:|setTransformationAnchor|
   #:|setTransformationMode|
   #:|setTransformations|
   #:|setTransform|
   #:|setTristate|
   #:|setType|
   #:|setUnderlineColor|
   #:|setUnderlineStyle|
   #:|setUnderline|
   #:|setUndoLimit|
   #:|setUndoRedoEnabled|
   #:|setUnifiedTitleAndToolBarOnMac|
   #:|setUniformItemSizes|
   #:|setUniformRowHeights|
   #:|setUniformValue(const char*,GLfloat)|
   #:|setUniformValue(const char*,GLint)|
   #:|setUniformValue(const char*,GLuint)|
   #:|setUniformValue(const char*,QColor)|
   #:|setUniformValue(const char*,QMatrix2x2)|
   #:|setUniformValue(const char*,QMatrix2x3)|
   #:|setUniformValue(const char*,QMatrix2x4)|
   #:|setUniformValue(const char*,QMatrix3x2)|
   #:|setUniformValue(const char*,QMatrix3x3)|
   #:|setUniformValue(const char*,QMatrix3x4)|
   #:|setUniformValue(const char*,QMatrix4x2)|
   #:|setUniformValue(const char*,QMatrix4x3)|
   #:|setUniformValue(const char*,QMatrix4x4)|
   #:|setUniformValue(const char*,QPoint)|
   #:|setUniformValue(const char*,QPointF)|
   #:|setUniformValue(const char*,QSize)|
   #:|setUniformValue(const char*,QSizeF)|
   #:|setUniformValue(const char*,QTransform)|
   #:|setUniformValue(const char*,QVector2D)|
   #:|setUniformValue(const char*,QVector3D)|
   #:|setUniformValue(const char*,QVector4D)|
   #:|setUniformValue(const char*...)|
   #:|setUniformValue(int,GLfloat)|
   #:|setUniformValue(int,GLint)|
   #:|setUniformValue(int,GLuint)|
   #:|setUniformValue(int,QColor)|
   #:|setUniformValue(int,QMatrix2x2)|
   #:|setUniformValue(int,QMatrix2x3)|
   #:|setUniformValue(int,QMatrix2x4)|
   #:|setUniformValue(int,QMatrix3x2)|
   #:|setUniformValue(int,QMatrix3x3)|
   #:|setUniformValue(int,QMatrix3x4)|
   #:|setUniformValue(int,QMatrix4x2)|
   #:|setUniformValue(int,QMatrix4x3)|
   #:|setUniformValue(int,QMatrix4x4)|
   #:|setUniformValue(int,QPoint)|
   #:|setUniformValue(int,QPointF)|
   #:|setUniformValue(int,QSize)|
   #:|setUniformValue(int,QSizeF)|
   #:|setUniformValue(int,QTransform)|
   #:|setUniformValue(int,QVector2D)|
   #:|setUniformValue(int,QVector3D)|
   #:|setUniformValue(int,QVector4D)|
   #:|setUniformValue(int...)|
   #:|setUniformValueArray(const char*,const QMatrix2x2*...)|
   #:|setUniformValueArray(const char*,const QMatrix2x3*...)|
   #:|setUniformValueArray(const char*,const QMatrix2x4*...)|
   #:|setUniformValueArray(const char*,const QMatrix3x2*...)|
   #:|setUniformValueArray(const char*,const QMatrix3x3*...)|
   #:|setUniformValueArray(const char*,const QMatrix3x4*...)|
   #:|setUniformValueArray(const char*,const QMatrix4x2*...)|
   #:|setUniformValueArray(const char*,const QMatrix4x3*...)|
   #:|setUniformValueArray(const char*,const QMatrix4x4*...)|
   #:|setUniformValueArray(const char*,const QVector2D*...)|
   #:|setUniformValueArray(const char*,const QVector3D*...)|
   #:|setUniformValueArray(const char*,const QVector4D*...)|
   #:|setUniformValueArray(const char*...)|
   #:|setUniformValueArray(int,const QMatrix2x2*...)|
   #:|setUniformValueArray(int,const QMatrix2x3*...)|
   #:|setUniformValueArray(int,const QMatrix2x4*...)|
   #:|setUniformValueArray(int,const QMatrix3x2*...)|
   #:|setUniformValueArray(int,const QMatrix3x3*...)|
   #:|setUniformValueArray(int,const QMatrix3x4*...)|
   #:|setUniformValueArray(int,const QMatrix4x2*...)|
   #:|setUniformValueArray(int,const QMatrix4x3*...)|
   #:|setUniformValueArray(int,const QMatrix4x4*...)|
   #:|setUniformValueArray(int,const QVector2D*...)|
   #:|setUniformValueArray(int,const QVector3D*...)|
   #:|setUniformValueArray(int,const QVector4D*...)|
   #:|setUniformValueArray(int...)|
   #:|setUniformValueArray|
   #:|setUniformValue|
   #:|setUpdateInterval|
   #:|setUpdatesEnabled|
   #:|setUrls|
   #:|setUrl|
   #:|setUseDesignMetrics|
   #:|setUseHighlightColors|
   #:|setUseSystemConfiguration.QNetworkProxyFactory|
   #:|setUserData|
   #:|setUserInfo|
   #:|setUserName|
   #:|setUserState|
   #:|setUserStyleSheetUrl|
   #:|setUser|
   #:|setUsesBigPixmap|
   #:|setUsesScrollButtons|
   #:|setUsesTextLabel|
   #:|setValidator|
   #:|setValue(QString...)|
   #:|setValue(int...)|
   #:|setValue|
   #:|setVector|
   #:|setVerticalAlignment|
   #:|setVerticalHeaderFormat|
   #:|setVerticalHeaderItem|
   #:|setVerticalHeaderLabels|
   #:|setVerticalHeader|
   #:|setVerticalPolicy|
   #:|setVerticalScrollBarPolicy|
   #:|setVerticalScrollBar|
   #:|setVerticalScrollMode|
   #:|setVerticalSpacing|
   #:|setVerticalStretch|
   #:|setViewBox(QRect)|
   #:|setViewBox(QRectF)|
   #:|setViewBox|
   #:|setViewMode|
   #:|setViewTransformEnabled|
   #:|setViewportMargins|
   #:|setViewportSize|
   #:|setViewportUpdateMode|
   #:|setViewport|
   #:|setView|
   #:|setVisible|
   #:|setVisualNavigation|
   #:|setWebGraphic.QWebSettings|
   #:|setWeekdayTextFormat|
   #:|setWeight|
   #:|setWhatsThis|
   #:|setWheelScrollLines.QApplication|
   #:|setWidgetResizable|
   #:|setWidget|
   #:|setWidth(QTextLength)|
   #:|setWidth(qreal)|
   #:|setWidthF|
   #:|setWidth|
   #:|setWindowCreated|
   #:|setWindowFilePath|
   #:|setWindowFlags|
   #:|setWindowFrameMargins|
   #:|setWindowIcon.QApplication|
   #:|setWindowIconText|
   #:|setWindowIcon|
   #:|setWindowModality|
   #:|setWindowModified|
   #:|setWindowOpacity|
   #:|setWindowRole|
   #:|setWindowState|
   #:|setWindowTitle|
   #:|setWindow|
   #:|setWizardStyle|
   #:|setWordSpacing|
   #:|setWordWrapMode|
   #:|setWordWrap|
   #:|setWorkingDirectory|
   #:|setWorldMatrixEnabled|
   #:|setWorldTransform|
   #:|setWrapAround|
   #:|setWrapMode|
   #:|setWrapping|
   #:|setWritable|
   #:|setWritingSystem|
   #:|setW|
   #:|setXOffset|
   #:|setXScale|
   #:|setX|
   #:|setYOffset|
   #:|setYScale|
   #:|setY|
   #:|setZScale|
   #:|setZValue|
   #:|setZoomFactor|
   #:|setZoomMode|
   #:|setZ|
   #:|settings|
   #:|setupData|
   #:|setupFinished|
   #:|setupStarted|
   #:|setupViewport|
   #:|shaderDestroyed|
   #:|shaderId|
   #:|shaderType|
   #:|shaders|
   #:|shadow|
   #:|shapeMode|
   #:|shape|
   #:|shear|
   #:|shortDayName.QDate|
   #:|shortMonthName.QDate|
   #:|shortcutContext|
   #:|shortcutId|
   #:|shortcuts|
   #:|shortcut|
   #:|shouldInterruptJavaScript|
   #:|showColumn|
   #:|showDropIndicator|
   #:|showExtension|
   #:|showFullScreen|
   #:|showGrid|
   #:|showLink|
   #:|showMaximized|
   #:|showMenu|
   #:|showMessage|
   #:|showMinimized|
   #:|showNextMonth|
   #:|showNextYear|
   #:|showNormal|
   #:|showPage|
   #:|showPopup|
   #:|showPreviousMonth|
   #:|showPreviousYear|
   #:|showRow|
   #:|showSection|
   #:|showSelectedDate|
   #:|showShaded|
   #:|showStatusText|
   #:|showSystemMenu|
   #:|showText.QToolTip|
   #:|showText.QWhatsThis|
   #:|showToday|
   #:|show|
   #:|sibling|
   #:|sidebarUrls|
   #:|signalsBlocked|
   #:|signal|
   #:|simplified|
   #:|singleStep|
   #:|sizeAdjustPolicy|
   #:|sizeConstraint|
   #:|sizeFromContents|
   #:|sizeHintChanged|
   #:|sizeHintForColumn|
   #:|sizeHintForIndex|
   #:|sizeHintForRow|
   #:|sizeHint|
   #:|sizeIncrement|
   #:|sizePolicy|
   #:|sizes|
   #:|size|
   #:|slerp.QQuaternion|
   #:|sliderMoved|
   #:|sliderPositionFromValue.QStyle|
   #:|sliderPosition|
   #:|sliderPressed|
   #:|sliderReleased|
   #:|sliderValueFromPosition.QStyle|
   #:|slopeAtPercent|
   #:|smallDecimalPoint|
   #:|smoothSizes|
   #:|socketDescriptor|
   #:|socketOption|
   #:|socketType|
   #:|softKeyRole|
   #:|sortByColumn|
   #:|sortCaseSensitivity|
   #:|sortChildren|
   #:|sortColumn|
   #:|sortIndicatorChanged|
   #:|sortIndicatorOrder|
   #:|sortIndicatorSection|
   #:|sortItems|
   #:|sortOrder|
   #:|sortRole|
   #:|sorting|
   #:|sort|
   #:|sourceBoundingRect|
   #:|sourceChanged|
   #:|sourceCode|
   #:|sourceIsPixmap|
   #:|sourceModel|
   #:|sourceState|
   #:|source|
   #:|spacerItem|
   #:|spacing|
   #:|spanAngle|
   #:|span|
   #:|specialValueText|
   #:|spec|
   #:|speed|
   #:|split.QItemSelection|
   #:|splitCell|
   #:|splitDockWidget|
   #:|splitPath|
   #:|splitterMoved|
   #:|splitter|
   #:|spontaneous|
   #:|spread|
   #:|sqlStatement|
   #:|squareToQuad.QTransform|
   #:|sslConfiguration|
   #:|sslErrors|
   #:|stackBefore|
   #:|stackUnder|
   #:|stackingMode|
   #:|stacks|
   #:|stack|
   #:|standaloneDayName|
   #:|standaloneMonthName|
   #:|standardButtons|
   #:|standardButton|
   #:|standardFormat|
   #:|standardIconImplementation|
   #:|standardIcon|
   #:|standardPalette|
   #:|standardPixmap|
   #:|standardSizes.QFontDatabase|
   #:|start(QString,QProcess::OpenMode)|
   #:|start(QString,QStringList)|
   #:|startAngle|
   #:|startCenterPoint|
   #:|startDetached.QProcess|
   #:|startDragDistance.QApplication|
   #:|startDragTime.QApplication|
   #:|startFrame|
   #:|startId|
   #:|startTimer|
   #:|startValue|
   #:|started|
   #:|startingUp.QCoreApplication|
   #:|start|
   #:|stateChanged|
   #:|state|
   #:|staticInstances.QPluginLoader|
   #:|staticMetaObject.QObject|
   #:|statusBarMessage|
   #:|statusBarVisibilityChangeRequested|
   #:|statusBar|
   #:|statusTip|
   #:|status|
   #:|stencilBufferSize|
   #:|stencil|
   #:|stepBy|
   #:|stepDown|
   #:|stepUp|
   #:|stereo|
   #:|stickyFocus|
   #:|stopped|
   #:|stops|
   #:|stop|
   #:|storageLocation.QDesktopServices|
   #:|strengthChanged|
   #:|strength|
   #:|stretchFactor|
   #:|stretchLastSection|
   #:|stretchSectionCount|
   #:|stretch|
   #:|strikeOutPos|
   #:|strikeOut|
   #:|stringList|
   #:|stringProperty|
   #:|string|
   #:|stripDelimitersImplementation|
   #:|stripDelimiters|
   #:|strokePath|
   #:|style.QApplication|
   #:|styleHint|
   #:|styleProperty|
   #:|styleSheet|
   #:|styleStrategy|
   #:|styleString(QFont)|
   #:|styleString(QFontInfo)|
   #:|styleString|
   #:|styles|
   #:|style|
   #:|subControlRect|
   #:|subElementRect|
   #:|subTitleFormat|
   #:|subTitle|
   #:|subWidgetRect|
   #:|subWindowActivated|
   #:|subWindowList|
   #:|subjectInfo(QByteArray)|
   #:|subjectInfo(QSslCertificate::SubjectInfo)|
   #:|subjectInfo|
   #:|submitAll|
   #:|submitPolicy|
   #:|submit|
   #:|subscribeToNotificationImplementation|
   #:|subscribeToNotification|
   #:|subscribedToNotificationsImplementation|
   #:|subscribedToNotifications|
   #:|substitute.QFont|
   #:|substitutes.QFont|
   #:|substitutions.QFont|
   #:|subtractStep|
   #:|subtracted|
   #:|suffix|
   #:|superClass|
   #:|supportedBits|
   #:|supportedDocumentFormats.QTextDocumentWriter|
   #:|supportedDragActions|
   #:|supportedDropActions|
   #:|supportedFormats.QMovie|
   #:|supportedPaperSizes|
   #:|supportedResolutions|
   #:|supportsExtension|
   #:|supportsFindBuffer|
   #:|supportsMessages.QSystemTrayIcon|
   #:|supportsSelection|
   #:|supportsThreadedFontRendering.QFontDatabase|
   #:|swallowContextMenuEvent|
   #:|swapBuffers|
   #:|swapInterval|
   #:|swapSections|
   #:|swipeAngle|
   #:|symLinkTarget.QFile|
   #:|symLinkTarget|
   #:|syncLayers|
   #:|syncX.QApplication|
   #:|sync|
   #:|system.QLocale|
   #:|systemEnvironment.QProcessEnvironment|
   #:|systemEnvironment.QProcess|
   #:|systemMenu|
   #:|systemProxyForQuery.QNetworkProxyFactory|
   #:|tabArray|
   #:|tabAt|
   #:|tabBar|
   #:|tabButton|
   #:|tabChangesFocus|
   #:|tabCloseRequested|
   #:|tabData|
   #:|tabIcon|
   #:|tabKeyNavigation|
   #:|tabMoved|
   #:|tabPositions|
   #:|tabPosition|
   #:|tabRect|
   #:|tabShape|
   #:|tabStopWidth|
   #:|tabStop|
   #:|tabTextColor|
   #:|tabText|
   #:|tabToolTip|
   #:|tabWhatsThis|
   #:|tabifiedDockWidgets|
   #:|tabifyDockWidget|
   #:|tableCellFormatIndex|
   #:|tableName|
   #:|tableWidget|
   #:|tables|
   #:|tabsClosable|
   #:|tagName|
   #:|takeAnimation|
   #:|takeAt|
   #:|takeChildren|
   #:|takeChild|
   #:|takeColumn|
   #:|takeFromDocument|
   #:|takeHorizontalHeaderItem|
   #:|takeItem|
   #:|takeRow|
   #:|takeTopLevelItem|
   #:|takeVerticalHeaderItem|
   #:|takeWidget|
   #:|tangentialPressure|
   #:|targetChanged|
   #:|targetObject|
   #:|targetStates|
   #:|targetState|
   #:|target|
   #:|temp.QDir|
   #:|tempPath.QDir|
   #:|terminate|
   #:|testAttribute.QCoreApplication|
   #:|testAttribute|
   #:|testBit|
   #:|testOption|
   #:|testRenderHint|
   #:|text(QClipboard::Mode)|
   #:|text(QString&)|
   #:|text.QToolTip|
   #:|textAlignment|
   #:|textBackgroundColor|
   #:|textChanged|
   #:|textColor|
   #:|textCursor|
   #:|textDirection|
   #:|textEchoMode|
   #:|textEdited|
   #:|textElideMode|
   #:|textFormat|
   #:|textFromValue|))
